### ISSUE TITLE
Test for slack module doesn't work in backend_tests

### ISSUE THREAD

**Issue by murinicanor** [errbotio/errbot#1033]
### I am...

* [ ] Reporting a bug

### I am running...

* Errbot version: 5.0.1
* OS version: Debian Stretch
* Python version: 3.5.3
* Using a virtual environment: no

### Issue description
The test-session fails when checking for the slack plugin- i guess it should just give a warning?

```
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /build/errbot-5.0.1, inifile: pytest.ini
collected 182 items / 1 errors

==================================== ERRORS ====================================
 ERROR collecting .pybuild/pythonX.Y_3.5/build/tests/backend_tests/slack_test.py 
tests/backend_tests/slack_test.py:47: in <module>
    @unittest.skipIf(not slack, "package slackclient not installed")
E   NameError: name 'slack' is not defined
------------------------------- Captured stderr --------------------------------
ERROR:errbot.backends.slack:Could not start the Slack back-end
Traceback (most recent call last):
  File "/build/errbot-5.0.1/errbot/backends/slack.py", line 28, in <module>
    from slackclient import SlackClient
ImportError: No module named 'slackclient'
CRITICAL:errbot.backends.slack:You need to install the slackclient support in order to use the Slack.
You can do `pip install errbot[slack]` to install it
ERROR:slack_test:Can't import backends.slack for testing
Traceback (most recent call last):
  File "/build/errbot-5.0.1/errbot/backends/slack.py", line 28, in <module>
    from slackclient import SlackClient
ImportError: No module named 'slackclient'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/errbot-5.0.1/.pybuild/pythonX.Y_3.5/build/tests/backend_tests/slack_test.py", line 13, in <module>
    from errbot.backends import slack
  File "/build/errbot-5.0.1/errbot/backends/slack.py", line 35, in <module>
    sys.exit(1)
SystemExit: 1
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.65 seconds ============================
```
### Steps to reproduce

try to run the tests without any slack modules installed

thanks for writing errbot!

cheers,
muri

**Comment by andrewthetechie** [comment]
#closeit
