### ISSUE TITLE
CERT: Invalid certificate trust chain

### ISSUE THREAD

**Issue by tobi7695** [errbotio/errbot#1044]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: Errbot version 5.0.1
* OS version: Ubuntu 16.04
* Python version: Python 3.5.2 (default, Nov 17 2016, 17:05:23)
* Using a virtual environment: yes

### Issue description

Please check log file attach :(

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

[errbot.txt](https://github.com/errbotio/errbot/files/1104906/errbot.txt)

### Additional info

If you have any more information, please specify it here.

**Comment by zoni** [comment]
> Using a virtual environment: yes

FYI: Your log shows errbot running from your global Python 3.5 environment, not a virtualenv.

As for your error. You need to make sure the server you're connecting to has a valid TLS certificate, trusted by your system. Alternatively, though insecure and strongly discouraged, you can set `XMPP_CA_CERT_FILE = None` to disable certificate validation.

**Comment by tobi7695** [comment]
Thanks for help!

2017-06-28 0:12 GMT+07:00 Nick Groenen <notifications@github.com>:

**Comment by tobi7695** [comment]
Where I can get virtualenv log? I found a log file err.log in "/var/log/err" but it is empty? :(

**Comment by zoni** [comment]
> Where I can get virtualenv log? I found a log file err.log in "/var/log/err" but it is empty? :(

What do you mean by "virtualenv log"?

Errbot logs to stdout (by default) and will optionally try to log to a file itself as well, depending on your settings (see the `config-template.py` file for examples, specifically the ones related to `BOT_LOG_xxx`).

**Comment by tobi7695** [comment]
@zoni Oh! Thanks you! I will try reconfig

**Comment by thundergreen** [comment]
Adding XMPP_CA_CERT_FILE = None has no effect. It checks the cert and says: 

14:09:18 ERROR    sleekxmpp.basexmpp        <TagSet object at 0xaa814b30 tags 0:32:16> not in asn1Spec: <OctetString sche
ma object at 0xaa82d9d0 encoding iso-8859-1 tagSet <TagSet object at 0xb5f67b90 tags 0:0:4>>
Traceback (most recent call last):                                                                                       
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1492, in _process
    if not self.__read_xml():                                                                                            
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1564, in __read_xml         
    self.__spawn_event(xml)                                                                                              
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1632, in __spawn_event      
    handler.prerun(stanza_copy)                                                                                          
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun        
    self.run(payload, True)                                                                                              
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run           
    self._pointer(payload)                                                                                               
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handl
e_starttls_proceed                                                                                                       
    if self.xmpp.start_tls():                                                                                            
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 889, in start_tls           
    cert.verify(self._expected_server_name, self._der_cert)                                                              
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/cert.py", line 134, in verify                   
    cert_names = extract_names(raw_cert)                                                                                 
  File "/root/.errbot-ve/lib/python3.5/site-packages/sleekxmpp/xmlstream/cert.py", line 73, in extract_names             
    asn1Spec=OctetString())[0]                                                                                           
  File "/root/.errbot-ve/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1318, in __call__                
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)                                                                        
pyasn1.error.PyAsn1Error: <TagSet object at 0xaa814b30 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0xaa8
2d9d0 encoding iso-8859-1 tagSet <TagSet object at 0xb5f67b90 tags 0:0:4>>                                               
14:09:18 DEBUG    sleekxmpp.xmlstream.xmlst reconnecting...
