### ISSUE TITLE
Groupchat error message when trying to send a message to a Hipchat room

### ISSUE THREAD

**Issue by eykd** [errbotio/errbot#1047]
### I am...

* [x] Reporting a bug(?)
* [x] Requesting help writing plugins(?)

### I am running...

* Errbot version: 5.0.1
* OS version: Ubuntu 16.04.2
* Python version: 3.6.1
* Using a virtual environment: yes

### Issue description

We've developed a plugin to remind our remote team about a weekly company event. The bot sends the message to a common room. We're using Hipchat, so we use an XMPP JID to identify the room. We recently upgrade to Errbot 5.0.1 from 2.x, so we started using `self.build_identifier` to convert the JID string to an `Identifier` object. However, every time the plugin activates to send the message, we get this traceback:

```
2017-06-29 11:29:58,341 ERROR    sleekxmpp.xmlstream.xmlstream Error processing stream handler: MUCError
Traceback (most recent call last):
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1684, in _event_runner
    handler.run(args[0])
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/plugins/xep_0045.py", line 187, in handle_groupchat_error_message
    self.xmpp.event("muc::%s::message_error" % msg['from'].bare, msg)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 701, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1511, in get_from
    return JID(self._get_attr('from'))
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
sleekxmpp.jid.InvalidJID: Domain contains illegal characters
Exception in thread event_thread_0:
Traceback (most recent call last):
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1684, in _event_runner
    handler.run(args[0])
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/plugins/xep_0045.py", line 187, in handle_groupchat_error_message
    self.xmpp.event("muc::%s::message_error" % msg['from'].bare, msg)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 701, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1511, in get_from
    return JID(self._get_attr('from'))
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
sleekxmpp.jid.InvalidJID: Domain contains illegal characters
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.6.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/pyenv/versions/3.6.1/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1688, in _event_runner
    orig.exception(e)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/stanza/rootstanza.py", line 78, in exception
    self.reply()
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/stanza/message.py", line 139, in reply
    StanzaBase.reply(self, clear)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1560, in reply
    self['to'] = self['from']
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 701, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1511, in get_from
    return JID(self._get_attr('from'))
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/path/to/lib/python3.6/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
sleekxmpp.jid.InvalidJID: Domain contains illegal characters
```

After this, the bot disconnects/is disconnected from Hipchat, and the process has to be stopped and restarted in order to reconnect.

### Steps to reproduce

Here is the plugin implementation (with the JID scrambled a bit):

```python
# -*- coding: utf-8 -*-
import logging
from datetime import timedelta
from errbot import BotPlugin

import arrow


class ChapelTime(BotPlugin):
    """Notify when it's time for chapel.
    """
    def check_for_chapel(self):
        now = arrow.now().to('US/Central')
        already_notified = self.last_notified and (now - self.last_notified) < timedelta(days=1)
        is_thursday = now.isoweekday() == 4
        if is_thursday and not already_notified:
            before_chapel_start = now.replace(hour=11, minute=29)
            chapel_start = now.replace(hour=11, minute=35)
            if before_chapel_start <= now <= chapel_start:
                logging.info("Notifying at %s", now)
                self.notify_for_chapel_time()
                self.last_notified = now

    def notify_for_chapel_time(self):
        room = self.build_identifier('71078_developer@conf.hipchat.com')  # Web Development
        self.send(room, text="http://i.imgur.com/9oFlFfG.gif")
        self.send(room, text="Stop! It's chapel time! http://...")

    def activate(self):
        super(ChapelTime, self).activate()
        self.last_notified = None
        self.start_poller(60, self.check_for_chapel)
```

### Additional info

The documentation for `build_identifier` just says that the structure of the string is backend-dependent, but there's no mention in the Hipchat backend documentation about what an identifier should look like. The room JID is valid, and is used elsewhere, e.g. for specifying rooms to join in `CHATROOM_PRESENCE`, and was used by `send()` in 2.x (w/o `build_identifier()`) to send a message to a room, so I'm not sure what I'm missing.

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
