### ISSUE TITLE
Can't send card with "to" params as Identifier.

### ISSUE THREAD

**Issue by inkhey** [errbotio/errbot#1107]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:5.1.2
* OS version: Debian Stretch
* Python version: 3.5.3
* Using a virtual environment: yes

### Issue description

When creating a plugin who send card, i got an error.
Look like, there is a bug somewhere. card.to should be an Identifier according to the documentation but it doesn't want my Identifier...

### Steps to reproduce

my card payload :
`
{'payload': {'to': '#projet', 'body': 'blabla, 'title': 'New content', 'color': 'green', 'link': 'http://perdu.com'}, 'type': 'IM_card'}
`

my webhook :
```
    @webhook
    def message(self, request):
        log.info(str(request))
        rooms = [str(room) for room in self.rooms()]
        if request['payload']['to'] in  rooms:
            if request['type'] == 'IM_txt':
                self.send(
                    self.build_identifier(request['payload']['to']),
                    request['payload']['txt']
                    )
## CHECK THIS PART
            elif request['type'] == 'IM_card':
                request['payload']['to'] = self.build_identifier(request['payload']['to']),
                self.send_card(**request['payload'])
        return "OK"
##
```

my error :

```
Traceback (most recent call last):
  File "/home/inkey/.local/share/virtualenvs/errbot/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/inkey/.local/share/virtualenvs/errbot/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/inkey/.local/share/virtualenvs/errbot/lib/python3.5/site-packages/errbot/core_plugins/wsview.py", line 100, in __call__
    response = self.func(data, **kwargs)
  File "/home/inkey/Documents/IM/errbot/plugins/myplugin/myplugin.py", line 30, in message
    self.send_card(**request['payload'])
  File "/home/inkey/.local/share/virtualenvs/errbot/lib/python3.5/site-packages/errbot/botplugin.py", line 564, in send_card
    self._bot.send_card(Card(body, frm, to, in_reply_to, summary, title, link, image, thumbnail, color, fields))
  File "/home/inkey/.local/share/virtualenvs/errbot/lib/python3.5/site-packages/errbot/backends/slack.py", line 704, in send_card
    to_humanreadable, to_channel_id = self._prepare_message(card)
  File "/home/inkey/.local/share/virtualenvs/errbot/lib/python3.5/site-packages/errbot/backends/slack.py", line 613, in _prepare_message
    to_humanreadable = msg.to.username
AttributeError: 'tuple' object has no attribute 'username'
```

**Comment by inkhey** [comment]
Just found the error myself, 

replace :
`
                request['payload']['to'] = self.build_identifier(request['payload']['to']),
`

with
`
                request['payload']['to'] = self.build_identifier(request['payload']['to'])`
