### ISSUE TITLE
Backup function fails with SyntaxError: literal_eval on file with statements

### ISSUE THREAD

**Issue by nicoddemus** [errbotio/errbot#1126]
To circumvent the corruption problem in #1125, I'm trying to use the backup functionality to restore my bot but without success.

I use the `!backup` command on the chat and the bot correctly saves a `backup.py` file with this contents:

```python
## This file is not executable on its own. use errbot -r FILE to restore your bot.

log.info("Restoring repo_manager.")
log.info("Restoring plugin_manager.")
...
```

The problem happens when trying to restore the backup, it fails with:

```
$ errbot -r
09:43:50 DEBUG    errbot.core               ErrBot init.
09:43:50 DEBUG    errbot.backends.base      Backend init.
09:43:50 DEBUG    errbot.core               created a thread pool of size 10.
09:43:50 DEBUG    errbot.core               Initializing backend storage
09:43:50 DEBUG    errbot.storage            Opening storage 'null_backend'
09:43:50 DEBUG    errbot.storage.shelf      Open shelf storage ./bot_data\null_backend.db
09:43:50 INFO     errbot.bootstrap          **** RESTORING the bot from ./bot_data\backup.py
Traceback (most recent call last):
  File "W:\Miniconda\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "W:\Miniconda\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bruno\errbot-esss\.env35\Scripts\errbot.exe\__main__.py", line 9, in <module>
  File "c:\users\bruno\errbot-esss\.env35\lib\site-packages\errbot\cli.py", line 297, in main
    bootstrap(backend, root_logger, config, restore)
  File "c:\users\bruno\errbot-esss\.env35\lib\site-packages\errbot\bootstrap.py", line 207, in bootstrap
    bot = setup_bot(bot_class, logger, config, restore)
  File "c:\users\bruno\errbot-esss\.env35\lib\site-packages\errbot\bootstrap.py", line 152, in setup_bot
    ast.literal_eval(f.read())
  File "W:\Miniconda\Lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "W:\Miniconda\Lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 4
    log.info("Restoring plugin_manager.")
      ^
SyntaxError: invalid syntax
```

This is strange because the bot is trying to use `literal_eval` on the file, but it clearly contains statements instead of a single literal. Perhaps I'm doing something wrong? Any hints appreciated.

**Comment by nicoddemus** [comment]
Changing the restore code from:

https://github.com/errbotio/errbot/blob/a07b9f1587bbad649d2b6023d7dd70dd8b787e13/errbot/bootstrap.py#L150-L153

To:

```python
        with open(restore) as f:
            exec(f.read(), {'log': log, 'bot': bot})
```

Fixes the issue for me:

```
09:51:49 DEBUG    errbot.storage            Closed storage 'Plugins'
09:51:49 DEBUG    errbot.storage            Closed storage 'null_backend'
Restore complete. You can restart the bot normally
```

Should I open a PR with the fix?

**Comment by zoni** [comment]
This would have been broken in https://github.com/errbotio/errbot/pull/893. I don't see how this functionality could ever work without a raw eval, so yes, please open a PR with that change.

I thought we had some CI integration for that, but I guess not...

**Comment by nicoddemus** [comment]
Will do, thanks for the feedback.
