### ISSUE TITLE
Text backend crashes when BOT_ADMINS is '#foo'

### ISSUE THREAD

**Issue by jayvdb** [errbotio/errbot#1135]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: master
* OS version: Fedora 27
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

Text backend crashes with `BOT_ADMINS = ['#foo']`

### Steps to reproduce

Edit config.py , appending  `BOT_ADMINS = ['#foo']`
clear cache
run `errbot`

### Additional info

```
20:02:03 DEBUG    errbot.bootstrap          Start serving commands from the text backend
────────────────────────────────────────────────────────────────────────────────
 You start as a bot admin in a one-on-one conversation with the bot.

    Context of the chat

• Use !inroom to switch to a room conversation.
• Use !inperson to switch back to a one-on-one conversation.
• Use !asuser to talk as a normal user.
• Use !asadmin to switch back as a bot admin.

    Preferences

• Use !ml to flip on/off the multiline mode (Enter twice at the end to send).
────────────────────────────────────────────────────────────────────────────────

Traceback (most recent call last):
..
  File "errbot/bootstrap.py", line 222, in bootstrap
    bot.serve_forever()
  File "errbot/backends/text.py", line 265, in serve_forever
    color = fg.red if self.user.person in self.bot_config.BOT_ADMINS[0] else fg.green
AttributeError: 'TextRoom' object has no attribute 'person'
```

**Comment by sijis** [comment]
I'm unable to reproduce this error.
I'm using `master` branch and using `Python 3.6.4`.

**Comment by andrewthetechie** [comment]
I am also unable to reproduce this. I tested a few branches to try to find if this was version related.

Test Docker Image: `python:3.6.6-slim`
Branches Test: 5.1, 5.2, master

**Comment by andrewthetechie** [comment]
#closeit
