### ISSUE TITLE
Slack: send_stream_request raises error when reading file

### ISSUE THREAD

**Issue by TheJokersThief** [errbotio/errbot#1175]
### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: 5.1.3
* OS version: Ubuntu 14.04
* Python version: 3.4.3
* Using a virtual environment: yes

### Issue description

When trying to send a file to the Slack API, it raises an error from the `requests` package that `TypeError: read() should return bytes`. 

This is just a plain text file that's being written to, closed and then read from to upload.

### Steps to reproduce

These are the steps in my python code that reproduces the issue:

```
timestamp = str(time.time())
tmp_file = "/tmp/job_output_{}.txt".format(timestamp)
file = open(tmp_file, 'w+')
file.write(job_output)
file.close()

self.send_stream_request(
    msg.frm,
    open(tmp_file, 'r'),
    name="job_output.txt"
)
```

### Additional info

Stacktrace:

```
Traceback (most recent call last):
  File "/opt/venvs/bot/lib/python3.4/site-packages/errbot/backends/slack.py", line 687, in _slack_upload
    'file': stream
  File "/opt/venvs/bot/lib/python3.4/site-packages/errbot/backends/slack.py", line 328, in api_call
    response = self.sc.api_call(method, **data)
  File "/opt/venvs/bot/lib/python3.4/site-packages/slackclient/client.py", line 88, in api_call
    response_body = self.server.api_call(method, timeout=timeout, **kwargs)
  File "/opt/venvs/bot/lib/python3.4/site-packages/slackclient/server.py", line 260, in api_call
    response = self.api_requester.do(self.token, method, kwargs, timeout=timeout)
  File "/opt/venvs/bot/lib/python3.4/site-packages/slackclient/slackrequest.py", line 104, in do
    proxies=self.proxies
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/opt/venvs/bot/lib/python3.4/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
TypeError: read() should return bytes
```

**Comment by sijis** [comment]
My first thought is to try this: `open(tmp_file, 'rb')`.

**Comment by TheJokersThief** [comment]
You are a saint and a scholar, sorry for the bother! Thanks so much!

**Comment by sijis** [comment]
No problem. I would probably also suggest using a context manager when dealing with files:
```
with open(tmp_file, 'w+') as f:
    f.write(job_output)
```
Using that you don't need to execute `file.close()`.
