### ISSUE TITLE
Issue when writing a test flow

### ISSUE THREAD

**Issue by prasadvelidi** [errbotio/errbot#1221]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: CentOS Linux release 7.4.1708 (Core)
* Python version:  Python 3.4.8
* Using a virtual environment: yes

### Issue description

I am trying to write a basic flow with in errbot. The following error is popping up and the plugin is not loading properly.

2018-05-21 08:12:29,656 ERROR    errbot.plugin_manager     Plugin hello failed at activation stage, deactivating it...
2018-05-21 08:12:29,656 ERROR    errbot.plugin_manager     Error loading hello
Traceback (most recent call last):
  File "/root/py3.4/lib/python3.4/site-packages/errbot/plugin_manager.py", line 528, in activate_non_started_plugins
    self.activate_plugin_with_version_check(pluginInfo)
  File "/root/py3.4/lib/python3.4/site-packages/errbot/plugin_manager.py", line 305, in activate_plugin_with_version_check
    self.activatePluginByName(name, BOTPLUGIN_TAG)
  File "/root/py3.4/lib/python3.4/site-packages/yapsy/PluginManager.py", line 563, in activatePluginByName
    plugin_to_activate.activate()
  File "/root/py3.4/lib/python3.4/site-packages/errbot/botplugin.py", line 390, in activate
    super().activate()
  File "/root/py3.4/lib/python3.4/site-packages/errbot/botplugin.py", line 174, in activate
    self.init_storage()
  File "/root/py3.4/lib/python3.4/site-packages/errbot/botplugin.py", line 167, in init_storage
    self.open_storage(self._bot.storage_plugin, self.name)
  File "/root/py3.4/lib/python3.4/site-packages/errbot/storage/__init__.py", line 33, in open_storage
    self._store = storage_plugin.open(namespace)
  File "/root/py3.4/lib/python3.4/site-packages/errbot/storage/shelf.py", line 49, in open
    **new_spot = os.path.join(config['basedir'], namespace + '.db')**
**TypeError: unsupported operand type(s) for +: 'method' and 'str'**

### Steps to reproduce

**(py3.4) bash-4.2# cat hello.flow**
```
[Core]
Name = hello_flow
Module = hello_flow
[Documentation]
Description = The hello flow that knows you better
[Python]
Version = 3+
```

**(py3.4) bash-4.2# cat hello_flow.py**
```
from errbot import botflow, FlowRoot, BotFlow, FLOW_END
class HelloFlow(BotFlow):
   @botflow
   def hello(self, flow: FlowRoot):
       hello = flow.connect('hello', auto_trigger=True)
       name = hello.connect('name')
       country = country.connect('country')
       country.connect(FLOW_END)
```

**(py3.4) bash-4.2# cat hello.plug**
```
[Core]
name = hello
module = hello
[Documentation]
description = Know the user a little better using this plugin
[Python]
version = 3
[Errbot]
min = 5.2.0
```

(py3.4) bash-4.2# cat hello.py

```
from errbot import BotPlugin, botcmd, botmatch
import time

class Hello(BotPlugin):
    @botcmd
    def hello(self, msg, args):
        yield "Hello There."
        time.sleep(2)
        yield "May i know your full name please ?"

    @botmatch(r'^.*$', flow_only=True)
    def name(self, msg, match):
        yield "Welcome " + match.string
        time.sleep(2)
        yield "Which country do you live in ?"

    @botmatch(r'^.*$', flow_only=True)
    def country(self, msg, match):
        yield "I hear that " + match.string + " is a nice place."
```

### Additional info
I am not sure why the TypeError is popping up when the flow itself is so basic. Can you please take a look and let me know where i was doing wrong ?

**Comment by prasadvelidi** [comment]
I kind of changes the names of the functions and it worked. Perhaps some collision is occurring when i select the function name as 'name' or something.
