### ISSUE TITLE
sleekxmpp.exceptions.IqTimeout with Hipchat

### ISSUE THREAD

**Issue by jereze** [errbotio/errbot#1227]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.3
* OS version: Ubuntu 14.04.5 LTS
* Python version: 3.4.3
* Using a virtual environment: yes

```
errbot==5.1.3
sleekxmpp==1.3.3
pyasn1==0.3.4
pyasn1-modules==0.1.4
hypchat==0.21
```

### Issue description

We use the Hipchat backend. Since 1 or 2 months, we get some errors when we (re)start the bot. The bot does not respond to any command. After ~30 minutes, it gets better and the bot responds.

```
2018-05-28 15:59:01,315 INFO     errbot.backends.hipchat   Joined room SFPD
2018-05-28 15:59:01,322 INFO     errbot.plugins.ChatRoom   Joining room 62742_gpu_crew@conf.hipchat.com with username Rexbot
2018-05-28 15:59:03,033 INFO     errbot.backends.hipchat   Found 62742_gpu_crew@conf.hipchat.com to be the room GPU crew, consider specifying this directly.
2018-05-28 15:59:03,246 WARNING  sleekxmpp.xmlstream.xmlstream Use of send mask waiters is deprecated.
2018-05-28 15:59:03,373 INFO     errbot.backends.hipchat   Joined room GPU crew
2018-05-28 15:59:03,374 INFO     errbot.core               Plugin activation done.
2018-05-28 16:01:40,285 ERROR    sleekxmpp.xmlstream.xmlstream Socket Error #104: Connection reset by peer
2018-05-28 16:01:40,286 WARNING  sleekxmpp.xmlstream.xmlstream Failed to send b'</stream:stream>'
2018-05-28 16:01:40,292 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2018-05-28 16:01:40,324 INFO     sleekxmpp.xmlstream.xmlstream Waiting for </stream:stream> from server
2018-05-28 16:01:40,325 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2018-05-28 16:03:37,571 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-29
2018-05-28 16:03:37,571 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 450, in incoming_message
    self.callback_message(msg)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 430, in callback_message
    filter(None.__ne__, [self._find_user(mention[1:], 'mention_name') for mention in possible_mentions])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 430, in <listcomp>
    filter(None.__ne__, [self._find_user(mention[1:], 'mention_name') for mention in possible_mentions])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_4526337@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-29" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:03:37,575 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:04:07,708 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2A
2018-05-28 16:04:07,709 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 442, in incoming_message
    msg.frm = self._build_room_occupant(xmppmsg['from'].full)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 424, in _build_room_occupant
    aclattr=self._find_user(resource, 'name'))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_2395381@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2A" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:04:07,709 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:04:12,695 ERROR    sleekxmpp.xmlstream.xmlstream Socket Error #104: Connection reset by peer
2018-05-28 16:04:12,695 WARNING  sleekxmpp.xmlstream.xmlstream Failed to send b'</stream:stream>'
2018-05-28 16:04:12,697 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2018-05-28 16:04:12,698 INFO     sleekxmpp.xmlstream.xmlstream Waiting for </stream:stream> from server
2018-05-28 16:04:12,699 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2018-05-28 16:04:37,820 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2B
2018-05-28 16:04:37,820 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 450, in incoming_message
    self.callback_message(msg)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 430, in callback_message
    filter(None.__ne__, [self._find_user(mention[1:], 'mention_name') for mention in possible_mentions])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 430, in <listcomp>
    filter(None.__ne__, [self._find_user(mention[1:], 'mention_name') for mention in possible_mentions])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_2395381@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2B" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:04:37,822 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:05:07,936 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2C
2018-05-28 16:05:07,937 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 442, in incoming_message
    msg.frm = self._build_room_occupant(xmppmsg['from'].full)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 424, in _build_room_occupant
    aclattr=self._find_user(resource, 'name'))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_2395381@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2C" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:05:07,939 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:05:38,060 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2D
2018-05-28 16:05:38,060 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 442, in incoming_message
    msg.frm = self._build_room_occupant(xmppmsg['from'].full)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 424, in _build_room_occupant
    aclattr=self._find_user(resource, 'name'))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_5326124@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2D" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:05:38,062 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:06:08,177 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2E
2018-05-28 16:06:08,177 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 442, in incoming_message
    msg.frm = self._build_room_occupant(xmppmsg['from'].full)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 424, in _build_room_occupant
    aclattr=self._find_user(resource, 'name'))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_5326124@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2E" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:06:08,179 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
2018-05-28 16:06:21,658 ERROR    sleekxmpp.xmlstream.xmlstream Could not connect to 52.91.183.185:5222. Socket Error #110: Connection timed out
2018-05-28 16:06:38,298 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_422e12aa-9466-42e2-b6c8-9dd864cd1b65-2F
2018-05-28 16:06:38,298 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f830c9d5ac8>>
Traceback (most recent call last):
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 442, in incoming_message
    msg.frm = self._build_room_occupant(xmppmsg['from'].full)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 424, in _build_room_occupant
    aclattr=self._find_user(resource, 'name'))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/hipchat.py", line 574, in _find_user
    identifier = self.build_identifier(userdetail['xmpp_jid'])
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 531, in build_identifier
    info = xep0030.get_info(jid=txtrep)
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/plugins/xep_0030/disco.py", line 370, in get_info
    timeout_callback=kwargs.get('timeout_callback', None))
  File "/home/rexbot/.errbot-virtualenv/lib/python3.4/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq to="62742_5326124@chat.hipchat.com" id="422e12aa-9466-42e2-b6c8-9dd864cd1b65-2F" type="get"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2018-05-28 16:06:38,299 WARNING  sleekxmpp.stanza.rootstanza You should catch IqTimeout exceptions
```

**Comment by PhilipWheatley47** [comment]
I also have this issue, but it does not recover.  I am using errbot on sleekxmpp.
If the "room" gets messages more than once every 30 minutes, it never disconnects.
If the room does not, it will loose connection, and I see sleekxmpp reconnecting.
However sleekxmpp does NOT seem to rejoin the rooms.
I can talk to the bot directly (not in a room) and it will obey commands.

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
