### ISSUE TITLE
TypeError: can't pickle module objects

### ISSUE THREAD

**Issue by anjandev** [errbotio/errbot#1253]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: Errbot version 9.9.9
* OS version: archlinux
* Python version: 3.7.0
* Using a virtual environment: yes

### Issue description

I am developing this plugin:

https://github.com/anjandev/err-remind

When I use the text backend and test it, my plugin works perfectly both in PM chatroom and multiuser chatroom.

When I use the XMPP backend it works in Private messages but does not work in multiple user chatrooms. In multiple user chatrooms, I get the following error when I type `!remind yesterday -> hello`:

```
Traceback (most recent call last):
  File "/home/anjan/.errbot-ve/lib/python3.7/site-packages/errbot-9.9.9-py3.7.egg/errbot/core.py", line 454, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/home/anjan/errbot-root/plugins/err-remind/remind.py", line 97, in remind
    self[reminder["id"]] = reminder
  File "/home/anjan/.errbot-ve/lib/python3.7/site-packages/errbot-9.9.9-py3.7.egg/errbot/storage/__init__.py", line 61, in __setitem__
    return self._store.set(key, item)
  File "/home/anjan/.errbot-ve/lib/python3.7/site-packages/errbot-9.9.9-py3.7.egg/errbot/storage/shelf.py", line 27, in set
    self.shelf[key] = value
  File "/usr/lib64/python3.7/shelve.py", line 124, in __setitem__
```

Keep in mind `!remind yesterday -> hello` or any variation of <date/time> and <message> in a private message to my bot, it works perfectly. The plugin works exactly as intended. 

Thank you.

**Comment by anjandev** [comment]
It seems that the data types that Im trying to store are:
```data: <class 'datetime.datetime'> message: <class 'str'> isUser: <class 'bool'> target: <class 'yapsy_loaded_plugin_XMPP_0.XMPPRoomOccupant'>```
for a XMPP MUC

For a private message, the data types Im trying to store are: 

```
data: <class 'datetime.datetime'> message: <class 'str'> isUser: <class 'bool'> target: <class 'yapsy_loaded_plugin_XMPP_0.XMPPPerson'>
```

It seems that some data types are pickable and others are not: https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

Im going to try to work around this but if anyone has any reccomendations, please let me know.

**Comment by anjandev** [comment]
converting changing ```msg.frm``` to ```str(msg.frm)``` yields the following error:


```Traceback (most recent call last):
  File "/home/anjan/.errbot-ve/lib/python3.7/site-packages/errbot/botplugin.py", line 274, in poller
    method(*args, **kwargs)
  File "/home/anjan/errbot-root/plugins/err-remind/remind.py", line 33, in send_reminders
    message=reminder['message']),
  File "/home/anjan/.errbot-ve/lib/python3.7/site-packages/errbot/botplugin.py", line 527, in send
    raise ValueError("identifier needs to be of type Identifier, the old string behavior is not supported")
ValueError: identifier needs to be of type Identifier, the old string behavior is not supported```

```msg.frm``` is used later in the program to send the message.

**Comment by anjandev** [comment]
Using http://errbot.io/en/latest/user_guide/plugin_development/messaging.html#sending-a-message-to-a-specific-user-or-room fixed it!

Cheers.
