### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rstrip' with errbot 6.0

### ISSUE THREAD

**Issue by bboe** [errbotio/errbot#1340]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug

### I am running...

* Errbot version: 6.0.0
* OS version: OS X 10.12.6 / Amazon Linux AMI
* Python version: 3.7.2 / 3.7.3
* Using a virtual environment: yes

### Issue description

I'm attempting to write a bot that depends on the `google-auth` package. I modified the `err-example` file to add just one line at the top:

```python
from google.oauth2 import service_account
```

When I attempt to load this plugin the following occurs:

```
21:22:35 ERROR    errbot.bootstrap          Some plugins failed to load:
Traceback (most recent call last):
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/errbot/plugin_manager.py", line 240, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(base_module_name, baseclass)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bboe/tmp/plugins/err-example/example.py", line 2, in <module>
    from google.oauth2 import service_account
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/oauth2/service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/_cryptography_rsa.py", line 28, in <module>
    import pkg_resources
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    for dist in working_set
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3269, in <genexpr>
    for dist in working_set
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2776, in activate
    declare_namespace(pkg)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2275, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2192, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'

21:22:35 DEBUG    errbot.bootstrap          Start serving commands from the text backend.
Some plugins failed to start during bot startup:
 Traceback (most recent call last):
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/errbot/plugin_manager.py", line 240, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(base_module_name, baseclass)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bboe/tmp/plugins/err-example/example.py", line 2, in <module>
    from google.oauth2 import service_account
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/oauth2/service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/init.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/google/auth/crypt/_cryptography_rsa.py", line 28, in <module>
    import pkg_resources
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 3241, in <module>
    @_call_aside
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 3225, in _call_aside
    f(args, *kwargs)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 3269, in _initialize_master_working_set
    for dist in working_set
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 3269, in <genexpr>
    for dist in working_set
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 2776, in activate
    declare_namespace(pkg)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 2275, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Users/bboe/.venvs/err/lib/python3.7/site-packages/pkg_resources/init.py", line 2192, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```

The error occurred across two different versions of python, on two different OSs. It seems the error goes away when using errbot 5.2.0.

**Comment by sijis** [comment]
Does the error happen without the Google module import?

Where is this `err-example` as that doesn't sound familiar to me.

Lastly, does this happen using the `master` branch?

**Comment by bboe** [comment]
`err-example` is in the `plugins` directory after doing `errbot --init`. It loads just fine without the import:

```
20:36:35 DEBUG    errbot.plugins.Example    Logger for plugin initialized...
```

I confirmed that the problem doesn't affect the latest master branch, so I'm going to close this issue.

In case you want any more information the the problem only occurred using the `from package.module import function` style, but doing `import package.module` was fine. Thanks for the tip about running the latest. Would you say the master branch is fairly stable?
