### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rstrip' when trying using JIRA

### ISSUE THREAD

**Issue by lordn-n** [errbotio/errbot#1379]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ X ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Ubuntu 18.10
* Python version: 3.7.3
* Using a virtual environment: yes

### Issue description
I'm attempting to write a bot that depends on JIRA package. I created a basic test plugin with just the jira import:
```
import jira
errbot import BotPlugin, botcmd

class Tests(BotPlugin):

    @botcmd(hidden=True)
    def testing(self, msg, args):
        response = 'Hi there'
        return f"{response}"
```

But I get this error:
```
ERROR    errbot.bootstrap          Some plugins failed to load:
Traceback (most recent call last):
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/errbot/plugin_manager.py", line 240, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(base_module_name, baseclass)
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bruno/projects/slackbot/plugins/tests/tests.py", line 1, in <module>
    import jira
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/jira/__init__.py", line 6, in <module>
    _v = VersionInfo('jira').semantic_version()
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pbr/version.py", line 462, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pbr/version.py", line 439, in _get_version_from_pkg_resources
    import pkg_resources
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3116, in _initialize_master_working_set
    for dist in working_set
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3116, in <genexpr>
    for dist in working_set
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2639, in activate
    declare_namespace(pkg)
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2176, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/opt/pyenvs/slackbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2096, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```
It's similar to #1340 but trying any kind of import `import jira.JIRA` or `from jira import JIRA` it failed the same way. I also tried with `master` branch and same result.

### Steps to reproduce
Just import jira module in any way

### Additional info
It used to work with errbot <6.*

**Comment by lordn-n** [comment]
Yes. It's a normal jira module
```
$ pip list | grep jira
jira                    2.0.0 
```

and it works within a python console
```
$ python
Python 3.7.3 (default, Apr  9 2019, 04:56:51) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
>>> print (jira.JIRA)
<class 'jira.client.JIRA'>
```

**Comment by sijis** [comment]
I also got an error when i loaded errbot up with your plugin.
```
23:12:12 ERROR    errbot.bootstrap          Some plugins failed to load:
...
  File "/home/data/git/github/errbot/plugins/issue1379/issue.py", line 1, in <module>
    import jira
ModuleNotFoundError: No module named 'jira'.
```
I then installed `jira` and the error went away.

```
 $  (e) test123-FhKy8IAs  /  tmp  test123  errbot
...

[@CHANGE_ME ➡ @errbot] >>> !issue1379
Hi there

```

Try using this plugin to see what modules you have installed
```
import subprocess

import jira

from errbot import BotPlugin, botcmd


class Issue1379(BotPlugin):
    @botcmd(hidden=True)
    def issue1379(self, msg, args):
        response = 'Hi there'
        return f"{response}"

    @botcmd
    def issue1379_modules(self, msg, args):

        installed = subprocess.call(['pip3', 'list'])
        return installed
```

Usage:
```
[@CHANGE_ME ➡ @errbot] >>> !issue1379 modules
Package                 Version    
----------------------- -----------
ansi                    0.1.3      
asn1crypto              0.24.0     
backcall                0.1.0      
beautifulsoup4          4.7.1      
certifi                 2019.6.16  
cffi                    1.12.3     
chardet                 3.0.4      
Click                   7.0        
colorlog                4.0.2      
cryptography            2.7        
daemonize               2.5.0      
decorator               4.4.0      
defusedxml              0.6.0      
dulwich                 0.19.11    
errbot                  6.1.0      
Flask                   1.0.3      
idna                    2.8        
ipython                 7.5.0      
ipython-genutils        0.2.0      
itsdangerous            1.1.0      
jedi                    0.13.3     
Jinja2                  2.10.1     
jira                    2.0.0      
Markdown                2.6.11     
MarkupSafe              1.1.1      
oauthlib                3.1.0      
parso                   0.4.0      
pbr                     5.4.2      
pexpect                 4.7.0      
pickleshare             0.7.5      
pip                     19.1.1     
prompt-toolkit          2.0.9      
ptyprocess              0.6.0      
pycparser               2.19       
Pygments                2.4.2      
pygments-markdown-lexer 0.1.0.dev39
PyJWT                   1.7.1      
pyOpenSSL               19.0.0     
requests                2.22.0     
requests-oauthlib       1.2.0      
requests-toolbelt       0.9.1      
setuptools              41.0.1     
six                     1.12.0     
slackclient             1.3.2      
soupsieve               1.9.1      
traitlets               4.3.2      
urllib3                 1.25.3     
waitress                1.3.0      
wcwidth                 0.1.7      
WebOb                   1.8.5      
websocket-client        0.54.0     
WebTest                 2.0.33     
Werkzeug                0.15.4     
wheel                   0.33.4     

[@CHANGE_ME ➡ @errbot] >>> !issue1379
Hi there

[@CHANGE_ME ➡ @errbot] >>> 
```

In short i'm not able to reproduce the problem.

**Comment by lordn-n** [comment]
I checked the `jira` package is correctly installed and listed under the `pip list` with the `subprocess` function. And it works properly in a new clean install of errbot.

I found a way to replicate my issue. On my bot I'm also using Akamai API, installing package `edgegrid-python>=1.1.1` causes the error, and uninstalling it works without issues. I have no idea why.

**Comment by sijis** [comment]
There is a weird combination with `edgegrid-python` and `jira` within errbot. The only thing that is strange is that edgegrid-python uses a [packaging-namespace feature](https://packaging.python.org/guides/packaging-namespace-packages/).

Quickly poking through all of this, I do not know where the issue may lie. It could *possibly* be within [errbot's plugin loading](https://github.com/errbotio/errbot/blob/master/errbot/plugin_info.py#L84)  but I do not know for certain.

**Comment by lordn-n** [comment]
The commit #1361 fix this issue :D
