### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rstrip' while trying using sklearn.feature_extraction

### ISSUE THREAD

**Issue by maxdogger** [errbotio/errbot#1381]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug

### I am running...

* Errbot version: 5.1.3
* OS version: macOS 10.14.6
* Python version: 3.7
* Using a virtual environment: no

### Issue description

AttributeError: 'PosixPath' object has no attribute 'rstrip' using the following imports

from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

I am not getting the error while using 
from sklearn.externals import joblib

### Steps to reproduce

Just import any of the package.module file

from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

### Additional info

Error:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/errbot/plugin_manager.py", line 240, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(base_module_name, baseclass)
  File "/anaconda3/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/<username>/errbot/plugins/Intent/intent.py", line 7, in <module>
    from sklearn.feature_extraction.text import TfidfTransformer
  File "/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/__init__.py", line 10, in <module>
    from . import text
  File "/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 30, in <module>
    from ..preprocessing import normalize
  File "/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/anaconda3/lib/python3.7/site-packages/sklearn/utils/testing.py", line 63, in <module>
    from nose.tools import raises as _nose_raises
  File "/anaconda3/lib/python3.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/anaconda3/lib/python3.7/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/anaconda3/lib/python3.7/site-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/anaconda3/lib/python3.7/site-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/anaconda3/lib/python3.7/site-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3219, in _initialize_master_working_set
    for dist in working_set
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3219, in <genexpr>
    for dist in working_set
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2726, in activate
    declare_namespace(pkg)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2252, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2169, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'

**Comment by lethonomia** [comment]
Commit #1361 fixed this issue in my build. I'm on the current release so I had to patch the change into my build.

**Comment by sijis** [comment]
The latest release should address this. If not, please reopen.
