### ISSUE TITLE
redirect loop on errbot.io 

### ISSUE THREAD

**Issue by drdee** [errbotio/errbot#1426]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: latest
* OS version: OSx Catalina
* Python version: 3.7.7
* Using a virtual environment: yes

### Issue description
visit https://errbot.readthedocs.io/en/latest/ and you are stuck in redirect loop 

### Steps to reproduce
```
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/errbot/core_plugins/vcheck.py", line 53, in _async_vcheck
    current_version_txt = self._get_version()
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/errbot/core_plugins/vcheck.py", line 45, in _get_version
    possible_versions = requests.get(HOME).json()
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/dvanliere/Development/mr-robot/.direnv/python-3.7.7/lib/python3.7/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by allyunion** [comment]
I get this too.

**Comment by gbin** [comment]
Looking into it. I removed completely the domain support from readthedocs, it should solves this but it needs to propagate first.
I wonder why it started to behave like that suddenly... @sijis did we change something recently?

**Comment by RO-29** [comment]
Same issue

**Comment by sijis** [comment]
@gbin I haven't changed any settings. I did rebuild after the release.

I can look at it in a bit further.

**Comment by sijis** [comment]
Everything seems to be working.
```
$ curl -s https://errbot.readthedocs.io/ -L | head

    <!doctype html>


<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Errbot &#8212; Err 9.9.9 documentation</title>
    <link rel="stylesheet" href="_static/err.css" type="text/css" />
$ curl -s https://errbot.io/ -L | head

    <!doctype html>


<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Errbot &#8212; Err 9.9.9 documentation</title>
    <link rel="stylesheet" href="_static/err.css" type="text/css" />
$ curl -s https://errbot.readthedocs.io/en/latest/ -L | head

    <!doctype html>


<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Errbot &#8212; Err 9.9.9 documentation</title>
    <link rel="stylesheet" href="_static/err.css" type="text/css" />
$ curl -s https://errbot.io/en/latest/ -L | head

    <!doctype html>


<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Errbot &#8212; Err 9.9.9 documentation</title>
    <link rel="stylesheet" href="_static/err.css" type="text/css" />
```

**Comment by gbin** [comment]
Yeah a "fixed it" by removing the domain support
