### ISSUE TITLE
Failing to connect to Slack

### ISSUE THREAD

**Issue by nicholasamorim** [errbotio/errbot#1454]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.4
* OS version: alpine 3.9
* Python version: 3.7
* Using a virtual environment: no (errbot lives alone in a docker container)

### Issue description

Out of nowhere, errbot started failing to connect to Slack. Error on `auth.test` api endpoint. Logs below:

```
2020-10-04 22:21:48,218 DEBUG    errbot.bootstrap          Start serving commands from the slack backend.
2020-10-04 22:21:48,219 INFO     errbot.backends.slack     Verifying authentication token
2020-10-04 22:21:48,222 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): slack.com:443
2020-10-04 22:21:53,228 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd89a470f90>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/auth.test (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd89a470f90>: Failed to establish a new connection: [Errno -3] Try again'))
```

### Steps to reproduce

Not sure how exactly. I simply have Slack configured and 1 plugin (err-stackstorm). It worked until yesterday - been using for 1 year already.

### Additional info

If you have any more information, please specify it here.

**Comment by nicholasamorim** [comment]
Nevermind, it was an issue on a particular node of the cluster where the container was being spawned. Apologies!
