### ISSUE TITLE
Blacklisting a plugin: 'BotPluginManager' object has no attribute 'bot'.

### ISSUE THREAD

**Issue by alpinweis** [errbotio/errbot#1476]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.5
* OS version: ubuntu 18.04
* Python version: 3.6.9
* Using a virtual environment: yes, errbot running in a docker container

### Issue description

Using a slack backend, I tried to disable the notifications coming from the `VersionChecker`

```
> Errbot App: Version 6.1.6 of Errbot is available. http://pypi.python.org/pypi/errbot/6.1.6. To disable this check do: !plugin blacklist VersionChecker
> User: !plugin blacklist VersionChecker
> Errbot App:  Plugin VersionChecker is now blacklisted.
```
After a while the following error message gets printed by errbot in the DM channel:
```
> Errbot App: Error: VersionChecker failed to activate: 'BotPluginManager' object has no attribute 'bot'.
```

**Comment by nzlosh** [comment]
Was there a stack trace with that error?

**Comment by alpinweis** [comment]
It looks like this happens when the RTM disconnects, which triggers re-upload/activation of all plugins. And the blacklisted/deactivated `VersionChecker` plugin produces an error. 

```
2020-11-18 16:26:39,788 DEBUG    root                      RTM disconnected
2020-11-18 16:26:39,788 ERROR    errbot.backends.slack     Error reading from RTM stream:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slackclient/server.py", line 283, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 310, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 327, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.6/dist-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.6/dist-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/errbot/backends/slack.py", line 398, in serve_once
    for message in self.sc.rtm_read():
  File "/usr/local/lib/python3.6/dist-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/usr/local/lib/python3.6/dist-packages/slackclient/server.py", line 301, in websocket_safe_read
    "Unable to send due to closed RTM websocket"
slackclient.server.SlackConnectionError: Unable to send due to closed RTM websocket
2020-11-18 16:26:39,788 DEBUG    errbot.backends.slack     Triggering disconnect callback
2020-11-18 16:26:39,788 INFO     errbot.core               Disconnect callback, deactivating all the plugins.

....

2020-11-18 16:26:40,136 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far).
2020-11-18 16:26:41,136 INFO     errbot.backends.slack     Verifying authentication token
2020-11-18 16:26:41,137 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): slack.com:443
2020-11-18 16:26:41,325 DEBUG    urllib3.connectionpool    https://slack.com:443 "POST /api/auth.test HTTP/1.1" 200 144
2020-11-18 16:26:41,327 DEBUG    errbot.backends.slack     Token accepted
2020-11-18 16:26:41,327 INFO     errbot.backends.slack     Connecting to Slack real-time-messaging API
2020-11-18 16:26:41,328 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): slack.com:443
2020-11-18 16:26:42,760 DEBUG    urllib3.connectionpool    https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 None
2020-11-18 16:26:43,267 DEBUG    root                      RTM connected
2020-11-18 16:26:44,291 INFO     errbot.backends.slack     Connected
2020-11-18 16:26:44,291 ERROR    errbot.backends.slack     Failed to look up Slack userid for alternate prefix "err": Cannot find user err.
2020-11-18 16:26:44,291 DEBUG    errbot.backends.slack     Converted bot_alt_prefixes: ('err',)
2020-11-18 16:26:44,291 DEBUG    errbot.backends.slack     Processing slack event: {'type': 'hello', 'region': 'us-west-2', 'start': True, 'host_id': 'xyz-123'}
2020-11-18 16:26:44,292 INFO     errbot.core               Activate internal commands
2020-11-18 16:26:44,292 INFO     errbot.plugin_manager     Activate bot plugins...

....

2020-11-18 16:26:44,304 ERROR    errbot.plugin_manager     Error loading VersionChecker.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/errbot/plugin_manager.py", line 365, in activate_non_started_plugins
    errors += f'Notice: {plugin.name} is blacklisted, ' \
AttributeError: 'BotPluginManager' object has no attribute 'bot'
```

**Comment by nzlosh** [comment]
Thank you for the extra detail.  It appears this issue could be related to https://github.com/errbotio/errbot/issues/1449.

**Comment by alpinweis** [comment]
Indeed, it looks like the same root cause - RTM/websocket disconnect. So it's a matter of gracefully handling the error in case of reactivating a blacklisted plugin?

**Comment by nzlosh** [comment]
Slack now forces connections to close from the server side.  This is a change in api behaviour which I think isn't being handled correctly by the slack backend plugin.  The error being raised by VersionChecker could be a corner case bug being triggered by not gracefully handling the disconnection.  I need to do some more testing around this to know for sure.
