### ISSUE TITLE
Connecting local mattermost server to errbot

### ISSUE THREAD

**Issue by devinpapalangi** [errbotio/errbot#1632]
Hey guys, so I have succesfully created a mattermost bot server in my private online server.

But now, I  want to move the bot to my local office server but it keep sending me an error saying that

mattermostdriver.exceptions.ResourceNotFound: Sorry, we could not find the page.

Can anyone help and tell me how to connect errbot to a local mattermost server? Thankyou

Here is my bot identity
![image](https://user-images.githubusercontent.com/105424353/223029377-dde1a586-6782-4e04-9e34-a8a2c7cd6dbf.png)

and this is my full console about the error
12:41:50 ERROR    mattermostdriver.websocke Sorry, we could not find the page.
12:41:50 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "d:\AG\bot-mattermost\.venv\Lib\site-packages\errbot\backends\base.py", line 868, in serve_forever
    if self.serve_once():
       ^^^^^^^^^^^^^^^^^
  File "D:\AG\bot-mattermost\errbot-mattermost-backend\..\errbot-mattermost-backend\src\err-backend-mattermost\err-backend-mattermost.py", line 347, in serve_once
    self.teamid = self.driver.teams.get_team_by_name(name=self.team)["id"]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\AG\bot-mattermost\.venv\Lib\site-packages\mattermostdriver\endpoints\teams.py", line 46, in get_team_by_name
    return self.client.get(
           ^^^^^^^^^^^^^^^^
  File "d:\AG\bot-mattermost\.venv\Lib\site-packages\mattermostdriver\client.py", line 193, in get
    response = self.make_request('get', endpoint, options=options, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\AG\bot-mattermost\.venv\Lib\site-packages\mattermostdriver\client.py", line 179, in make_request
    raise ResourceNotFound(message) from None
mattermostdriver.exceptions.ResourceNotFound: Sorry, we could not find the page.
12:41:50 INFO     errbot.backends.base      Reconnecting in 601 seconds (13 attempted reconnections so far).

**Comment by keenborder786** [comment]
Hey I am looking into this issue.

**Comment by keenborder786** [comment]
Can you please make sure their is not firewall which is blocking the connection?
