### ISSUE TITLE
Getting a KeyError: 'team_id'

### ISSUE THREAD

**Issue by jpamintuan** [errbotio/errbot#1664]
**Describe the bug**
Our errbot for slack was working for almost 2 years but stopped working yesterday (10/24/2023). I went to the errbot.log file and found this error  KeyError: 'team_id'

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/errbot/backends/base.py", line 868, in serve_forever
    if self.serve_once():
  File "/usr/local/lib/python3.9/dist-packages/errbot/backends/err-backend-slackv3/slackv3.py", line 273, in serve_once
    self.bot_identifier = SlackPerson(self.slack_web, self.auth["user_id"])
  File "/usr/local/lib/python3.9/dist-packages/errbot/backends/err-backend-slackv3/_slack/person.py", line 50, in __init__
    self._cache_user_info()
  File "/usr/local/lib/python3.9/dist-packages/errbot/backends/err-backend-slackv3/_slack/person.py", line 98, in _cache_user_info
    team_res = self._webclient.team_info(team=res["user"]["team_id"])
KeyError: 'team_id'
12:39:44 INFO     errbot.backends.base      Reconnecting in 8 seconds (2 attempted reconnections so far).`

**To Reproduce**
To reproduce, I went to CLI and typed "errbot", this should start errbot instance

**Expected behavior**
Expected behaviors should be no errors after running "errbot"

**Screenshots**

**Environment (please complete the following information):**
- Errbot version:
- OS version:Ubuntu 20.04
- Python version: 3.8.10
- Using a virtual environment: NO
- Using Docker: YES

**Comment by nzlosh** [comment]
Does using the latest version of the slackv3 plugin resolve the issue?  It looks like you've encountered the issue mentioned here https://github.com/errbotio/err-backend-slackv3/issues/96

**Comment by jpamintuan** [comment]
Yes it did! thanks
