### ISSUE TITLE
TypeError: String or Integer object expected for key, unicode found

### ISSUE THREAD

**Issue by DazWorrall** [errbotio/errbot#232]
Ubuntu 12.04
Python 2.7.3

On first run I get

```
Traceback (most recent call last):
  File "/root/.virtualenvs/errbot/bin/err.py", line 191, in <module>
    main(bot_class, logger)
  File "/root/.virtualenvs/errbot/local/lib/python2.7/site-packages/errbot/main.py", line 38, in main
    holder.bot = bot_class(**BOT_IDENTITY)
  File "/root/.virtualenvs/errbot/local/lib/python2.7/site-packages/errbot/backends/xmpp.py", line 147, in __init__
    super(XMPPBackend, self).__init__(*args, **kwargs)
  File "/root/.virtualenvs/errbot/local/lib/python2.7/site-packages/errbot/errBot.py", line 70, in __init__
    if CONFIGS not in self:
  File "/root/.virtualenvs/errbot/lib/python2.7/_abcoll.py", line 348, in __contains__
    self[key]
  File "/root/.virtualenvs/errbot/local/lib/python2.7/site-packages/errbot/storage.py", line 41, in __getitem__
    return self.shelf.__getitem__(key)
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found
```

The constants in errBot.py look like this:

```
CONFIGS = u'configs' if PY2 else u'configs'
REPOS = u'repos' if PY2 else u'repos'
BL_PLUGINS = u'bl_plugins' if PY2 else u'bl_plugins'
```

The PY2 versions of those strings should be bytestrings I guess, looking at HEAD (https://github.com/gbin/err/blob/4716bd0ce636be1c73cdd759bd0b58562cd85dba/errbot/errBot.py#L49-L51). 3to2 bug perhaps? If I simply drop the 'u' on those constants I startup fine.

**Comment by zahnp4sta** [comment]
Hey,
 I keep getting this error today.

Any ideas what i could have fucked up ?

Cheers

**Comment by zoni** [comment]
@zahnp4sta could you open a new issue please with (1) the version of errbot you are running and (2) the full traceback you're getting?

Given the age of this issue it is probably caused by something else.
