### ISSUE TITLE
blacklisted plugin message is messed up

### ISSUE THREAD

**Issue by ramonamis** [errbotio/errbot#554]
```
[11:28] Hilda-san (Bot): Notice: ! is blacklisted, use Launchpad plugin unblacklist Launchpad to unblacklist it
[11:28] Ramona Misaila: !plugin unblacklist Launchpad
[11:28] Hilda-san (Bot): This command requires bot-admin privileges
		Plugin Launchpad removed from blacklist
```

Hello,

It seems to me that the notification one gets at bot restart when a plugin is blacklisted does not make too much sense in English. I think it would be much better the way it was in previous versions. For example 2.2.0 had: ```Notice: Jenkins is blacklisted, use !load Jenkins to unblacklist it ``` which is much more clear. If you agree with the wording on that i can prepare a fix pr for this. 

Also,  ```This command requires bot-admin privileges``` yield on unblacklist command first made me think i am not bot admin or something. maybe that can be removed. 

I just upgraded to 3.2.0 from 2.2.0 and I like it very much. I can't actually call it an "upgrade" because i had to remove the virtual env and recreate it due to this error: https://gist.github.com/ramonamis/940d53123a2711aaf34e. Maybe the issue could have been solved otherwise but recreating the virtualenv seemed the fastest and easiest.

Another issue i had was with joining rooms using the hipchat backend. For some weird reason the hipchat api did not return the xmpp jid one room i tried to join and then errbot was telling me:
```python
Traceback (most recent call last):
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/errbot/core_plugins/chatRoom.py", line 33, in callback_connect
    self._join_room(room)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/errbot/core_plugins/chatRoom.py", line 47, in _join_room
    self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/errbot/botplugin.py", line 448, in query_room
    return self._bot.query_room(room=room)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/errbot/backends/hipchat.py", line 425, in query_room
    raise RoomDoesNotExistError(u"No room with JID {} found.".format(room))
RoomDoesNotExistError: No room with JID *************@conf.hipchat.com found.
```
Seems like for hipchat backend to join room the safest and easiest way to do so is to specify the rooms by names: ```CHATROOM_PRESENCE = (u'Ops', u'ReleaseChat',)``` However, for acl's it did not work this way, i still had to use xmpp jid :(. The hipchat backend is looking for room names though: https://github.com/errbotio/errbot/blob/master/errbot/backends/hipchat.py#L422

I am confident this is a quite long thread, we can split it if you want, though i think the only real "issue" lays in the first paragraph. 

I really like the new version of err, thanks for the upgrade! :+1:

**Comment by gbin** [comment]
Thanks for the feedback ! Indeed please split the issues so we can work on them independently.

**Comment by gbin** [comment]
Please open split workable issues.
