### ISSUE TITLE
Ignore all input that cannot be decoded

### ISSUE THREAD

**Issue by perlop** [errbotio/errbot#569]
Hello. I am getting an UnicodeDecodeError randomly on irc. I found a solution at https://pypi.python.org/pypi/irc. But I don't know how to apply it to errbot.

**Comment by mrshu** [comment]
@perlop Would you happen to have examples of input that I could use to create a test?

In any case would you mind taking a look at #570? Thanks!

**Comment by perlop** [comment]
Hi I downloaded https://github.com/errbotio/errbot/tree/45299a0498d9d0fdcfe86c3326a71acf16177442 and I have been on IRC for about 5 hours. I think it is should be resolved. Here is part of the log with level debug from when I had the exception. 

19:07:56 DEBUG    irc.client                FROM SERVER: :CR-CAROLINA|NEW!~CAROLINA@Brought.To.You.By.NIBL PRIVMSG #HorribleSubs :From North Carolina * [107M] * [HorribleSubs] Kagewani - 13 [720p].mkv * 03/MSG CR-CAROLINA|NEW XDCC SEND 1299
19:07:56 DEBUG    irc.client                _dispatcher: all_raw_messages
19:07:56 DEBUG    irc.client                command: pubmsg, source: CR-CAROLINA|NEW!~CAROLINA@Brought.To.You.By.NIBL, target: #HorribleSubs, arguments: ['\x02From North Carolina\x02 * [107M] * [HorribleSubs] Kagewani - 13 [720p].mkv * \x02\x0303/MSG CR-CAROLINA|NEW XDCC SEND 1299\x03\x0f'], tags: None
19:07:56 DEBUG    irc.client                _dispatcher: pubmsg
19:07:56 DEBUG    errbot.errBot             *** frm = CR-CAROLINA|NEW!None #HorribleSubs
19:07:56 DEBUG    errbot.errBot             *** username = CR-CAROLINA|NEW
19:07:56 DEBUG    errbot.errBot             *** type = groupchat
19:07:56 DEBUG    errbot.errBot             *** text = From North Carolina * [107M] * [HorribleSubs] Kagewani - 13 [720p].mkv * 03/MSG CR-CAROLINA|NEW XDCC SEND 1299
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on ACLS
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on Help
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on PluginExample
...
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on VersionChecker
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on HelloWorld
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on Utils
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on Backup
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on Health
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on ChatRoom
19:07:56 DEBUG    errbot.errBot             Trigger callback_message on Plugins
19:07:57 WARNING  irc.buffer                
Unknown encoding encountered. See 'Decoding Input'
....
Traceback (most recent call last):
  File "/usr/bin/errbot", line 9, in <module>
    load_entry_point('errbot==3.2.2', 'console_scripts', 'errbot')()
  File "/usr/lib/python3.4/site-packages/errbot/err.py", line 258, in main
    main(backend, logger, config, restore)
  File "/usr/lib/python3.4/site-packages/errbot/main.py", line 87, in main
    bot.serve_forever()
  File "/usr/lib/python3.4/site-packages/errbot/backends/irc.py", line 491, in serve_forever
    self.conn.start()
  File "/usr/lib/python3.4/site-packages/irc/bot.py", line 265, in start
    super(SingleServerIRCBot, self).start()
  File "/usr/lib/python3.4/site-packages/irc/client.py", line 1247, in start
    self.reactor.process_forever()
  File "/usr/lib/python3.4/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/usr/lib/python3.4/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/lib/python3.4/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/lib/python3.4/site-packages/irc/client.py", line 583, in process_data
    for line in self.buffer:
  File "/usr/lib/python3.4/site-packages/irc/buffer.py", line 102, in lines
    self.handle_exception()
  File "/usr/lib/python3.4/site-packages/irc/buffer.py", line 100, in lines
    yield line.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 56: invalid start byte

Another


2015-12-25 19:45:39,007 DEBUG    irc.client                FROM SERVER: :Archchanczellor!~Archchanc@E4B8027D:B815407B:12388AEC:IP QUIT :Read error: Connection reset by peer
2015-12-25 19:45:39,008 DEBUG    irc.client                _dispatcher: all_raw_messages
2015-12-25 19:45:39,008 DEBUG    irc.client                command: quit, source: Archchanczellor!~Archchanc@E4B8027D:B815407B:12388AEC:IP, target: None, arguments: ['Read error: Connection reset by peer'], tags: None
2015-12-25 19:45:39,009 DEBUG    irc.client                _dispatcher: quit
2015-12-25 19:45:44,694 DEBUG    irc.client                FROM SERVER: :purgoiser!~purgoiser@F036BA68.76BB93C7.8A7447E2.IP JOIN :#HorribleSubs
2015-12-25 19:45:44,694 DEBUG    irc.client                _dispatcher: all_raw_messages
2015-12-25 19:45:44,695 DEBUG    irc.client                command: join, source: purgoiser!~purgoiser@F036BA68.76BB93C7.8A7447E2.IP, target: #HorribleSubs, arguments: [], tags: None
2015-12-25 19:45:44,695 DEBUG    irc.client                _dispatcher: join
2015-12-25 19:45:45,693 WARNING  irc.buffer                
Unknown encoding encountered. See 'Decoding Input'
in https://pypi.python.org/pypi/irc for details.

**Comment by mrshu** [comment]
@perlop Thanks for confirming the fix, @gbin it's your call now =)
