### ISSUE TITLE
UnicodeEncodeError when using Text backend on ubuntu docker vm

### ISSUE THREAD

**Issue by anitawoodruff** [errbotio/errbot#590]
I tried setting up an ubuntu docker image for my bot, with no plugins for now, and it works fine with the XMPP backend, but when I type any command (e.g. 'status', 'help') using the Text backend, I just get the following error:
```
09:42:31 ERROR    errbot.errBot             An error happened while processing a message ("status"): Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 441, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 193, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 172, in split_and_send_message
    self.send_message(partial_message)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 90, in send_message
    print(bar.format(mode='MD  '))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
"
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 441, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 193, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 172, in split_and_send_message
    self.send_message(partial_message)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 90, in send_message
    print(bar.format(mode='MD  '))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
09:42:31 ERROR    errbot.bundled.threadpool Command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 441, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 193, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 172, in split_and_send_message
    self.send_message(partial_message)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 90, in send_message
    print(bar.format(mode='MD  '))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/bundled/threadpool.py", line 162, in run
    result = request.callable(*request.args, **request.kwds)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 447, in _execute_and_send
    self.send_simple_reply(mess, self.MSG_ERROR_OCCURRED + ':\n %s' % e, private)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 193, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 172, in split_and_send_message
    self.send_message(partial_message)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 90, in send_message
    print(bar.format(mode='MD  '))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```
Here are the contents of my Dockerfile:
```
FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install python3-pip
RUN apt-get -y install libffi-dev # required for cryptography (errbot dep)
RUN apt-get -y install libssl-dev # req for pycparser (errbot dep)
RUN pip3 install --upgrade six # runtime dep of errbot (>= 1.7)
RUN pip3 install errbot # https://github.com/errbotio/errbot/archive/master.zip
RUN mkdir /var/lib/err && mkdir /var/log/err
RUN mkdir /src
COPY ./config.py /src/
COPY ./credentials.cfg /src/
WORKDIR /src
CMD ["errbot", "-T"]
```

(The same thing happens if I comment out the CMD line, run with bash, and start errbot manually)

I get this issue both with the latest published errbot version (3.2.2) and the latest master zip.

**Comment by gbin** [comment]
It looks like the default locale stays at "POSIX" on ubuntu/docker.
Try to add:
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
in the dockerfile.

**Comment by anitawoodruff** [comment]
Woop, that worked, thanks!

Guess this can be closed then as it was an issue with my docker machine, not errbot.

**Comment by gbin** [comment]
I have added a warning in the log on errbot at runtime so users don't get surprised, maybe it is not in the stable yet, if you can test if it triggers in your case that would marvellous !

**Comment by anitawoodruff** [comment]
I just tried by installing with `pip3 install https://github.com/errbotio/errbot/archive/master.zip` without the above fix, and didn't see a warning.. do I need to build errbot from source to get your changes?

**Comment by gbin** [comment]
It is at the load time of https://github.com/errbotio/errbot/blob/master/errbot/err.py (around L44) so definitely in master.zip you used !

It should warn you when you start the bot.

It might not make sense to warn at install time because it is user dependent (root might be POSIX and install it but the user used for errbot is utf-8).

Thanks again for you help!

**Comment by anitawoodruff** [comment]
Nope, definitely no warning. And I think I know why:
 if I run
`import sys`
`sys.getdefaultencoding()`
in a python3 shell on the docker machine, it returns `utf-8` even when I don't include any of your lines to set the encoding. i.e. it is giving the error but still returning default encoding as `utf-8`, which is weird!

By the way, I found that I only actually needed 2 lines to get rid of the errors:
`RUN locale-gen en_US.UTF-8  `
and (`ENV LANG en_US.UTF-8 ` or `ENV LC_ALL en_US.UTF-8  `), either seemed to work

**Comment by anitawoodruff** [comment]
Perhaps you could instead check `locale.getdefaultlocale() doesn't return `(None, None)` before printing the warning? (See http://stackoverflow.com/questions/3425294/how-to-detect-the-os-default-language-in-python) 

That call returns `(None, None)` for me without your lines to set the encoding, but `('en_US', 'UTF-8')` if I do set the encoding, via either of the ways I mentioned in my last post.

**Comment by gbin** [comment]
Oh OK, would you like to send a quick PR for the proposed çhange?

**Comment by anitawoodruff** [comment]
would love to but might not be able to for a few weeks - work stuff :[
