### ISSUE TITLE
Restore from backup new issue

### ISSUE THREAD

**Issue by ethan-eb** [errbotio/errbot#602]
There are now two issues, one is the same as in #588 ... first problem when restoring a backup is

    File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 89, in setup_bot
        if u'repos' in bot:
    TypeError: argument of type 'NullBackend' is not iterable

Looks like it needs to be `if 'repos' in bot.plugin_manager` ... once that is fixed, the #588 issue is still there for python 2.7: `TypeError: String or Integer object expected for key, unicode found` 

I will try the `bytes()` fix and submit a PR

**Comment by ethan-eb** [comment]
Ok, the fixes for the issues above seem to work. However, I generated a new backup file, then tried to restore and got

    Traceback (most recent call last):
      File "/usr/local/bin/errbot", line 9, in <module>
        load_entry_point('errbot==9.9.9', 'console_scripts', 'errbot')()
      File "/usr/local/lib/python2.7/dist-packages/errbot/err.py", line 262, in main
        main(backend, logger, config, restore)
      File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 118, in main
        bot = setup_bot(bot_class, logger, config, restore)
      File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 94, in setup_bot
        exec(f.read())
      File "<string>", line 12, in <module>
    AttributeError: 'NoneType' object has no attribute 'plugin_object'

it's while exec-ing the backup file so I guess it's the `pobj = bot.plugin_manager.get_plugin_by_name("Health").plugin_object` still investigating, but if you have a solution I'm all ears...

**Comment by gbin** [comment]
fixed on master
