### ISSUE TITLE
Repo manager cannot update list

### ISSUE THREAD

**Issue by jasedit** [errbotio/errbot#623]
This is using master with Python 3.5, I somehow lost my list of plugins installed, so I attempted to install a repository by executing `!repos install https://github.com/jasedit/errbot-catfacts.git` and got the following error log:
```
16:20:33 INFO     errbot.errBot             Processing command 'repos_install' with parameters 'https://github.com/jasedit/errbot-catfacts.git' from @jasedit
16:20:33 INFO     errbot.repo_manager       No repo index, creating it.
16:20:33 INFO     errbot.repo_manager       Index is too old, update it.
16:20:33 ERROR    errbot.repo_manager       Could not update from source http://repos.errbot.io/repos.json, keep the index as it is.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jpz/Projects/errbot2/lib/python3.5/site-packages/errbot/repo_manager.py", line 98, in index_update
    src_file = urlopen(url=source, timeout=10)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
16:20:33 INFO     errbot                    webhooks:  Flag to bind /echo to echo

╌╌[MD  ]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...


╌╌[HTML]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
<p>A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...</p>


╌╌[TEXT]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...

╌╌[IM  ]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...

╌╌[ANSI]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...

╌╌[BORDERLESS]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
A new plugin repository has been installed correctly from https://github.com/jasedit/errbot-catfacts.git. Refreshing the plugins commands...
```

But the new plugin is not loaded, and does not show up in the plugins status. Attempting to direct a web browser to http://repos.errbot.io/repos.json produces an ERR_NAME_NOT_RESOLVED.

**Comment by gbin** [comment]
yep, we are in the process to host this file, meanwhile you can generate one from https://github.com/errbotio/errbot/blob/master/tools/plugin-gen.py 

The content of the file should look like this: https://github.com/errbotio/errbot/blob/master/tests/base_backend_tests.py#L30

You can point your config to it like this: https://github.com/errbotio/errbot/blob/master/tests/base_backend_tests.py#L68

I hope it helps while we find a good home for this file online :)

**Comment by gbin** [comment]
I have deployed a repos,json online.
It is still http but at least it should work.
you need to pull master.

Thanks for you for your patience !
