### ISSUE TITLE
HipChat/XMPP backend fails to parse identifiers in errbot 4.0.1

### ISSUE THREAD

**Issue by pendragon-** [errbotio/errbot#669]
```
21:13:05 INFO     errbot.errBot             Processing command 'git_following' with parameters '' from xxxxx_xxxxxxx@chat.hipchat.com/web||proxy|proxy-b112.hipchat.com|5262
21:13:06 ERROR    errbot.errBot             An error happened while processing a message ("!git following"): Traceback (most recent call last):
  File "/.../.virtualenvs/errbot4/lib/python3.5/site-packages/errbot/errBot.py", line 455, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/.../.virtualenvs/errbot4/lib/python3.5/site-packages/errbot/errBot.py", line 208, in send_simple_reply
    reply = self.build_reply(mess, text, private)
  File "/.../.virtualenvs/errbot4/lib/python3.5/site-packages/errbot/backends/hipchat.py", line 452, in build_reply
    node, domain, resource = split_identifier(self.username_to_jid(response.to.client))
  File "/.../.virtualenvs/errbot4/lib/python3.5/site-packages/errbot/backends/xmpp.py", line 411, in split_identifier
    split_jid = txtrep.split('@')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by zoni** [comment]
I'm so sorry about this. :cry: 
I swear I tested the HipChat backend thoroughly, but somehow I still missed this. :disappointed: 

It should be fixed in master and on the 4.0 branch though. Would you have an opportunity to verify this?

**Comment by pendragon-** [comment]
No problem, thanks for fixing it! I'll check it later today and update this.

**Comment by pendragon-** [comment]
Works fine.
