### ISSUE TITLE
!repos search broken

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#673]
I can't immediately see what's caused this, I've seen it working fine before. But:

```
20:02:48 DEBUG    errbot.backends.telegram  Getting updates with offset 677258962
20:02:48 INFO     errbot.repo_manager       Index is too old, update it.
20:02:48 DEBUG    errbot.repo_manager       Update from local source tools/repos.json...
20:02:48 DEBUG    errbot.repo_manager       Stored 291 repo entries.
20:02:48 ERROR    errbot.errBot             An error happened while processing a message (".repos search converter"): Traceback (most recent call last):
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 455, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 428, in process_template
    return tenv().get_template(template_name + '.md').render(**template_parameters)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zoni/Workspace/Projects/err/errbot/core_plugins/templates/repos2.md", line 6, in top-level template code
    {% for repo in repos %}         | {{('**'+repo.entry_name+'**').ljust(22)}} | {{repo.documentation}}
  File "/home/zoni/Workspace/Projects/err/errbot/repo_manager.py", line 153, in search_repos
    if query_work_set.intersection(tokenizeJsonEntry(plugin)):
  File "/home/zoni/Workspace/Projects/err/errbot/repo_manager.py", line 66, in tokenizeJsonEntry
    return set(find_words.findall(' '.join((word.lower() for word in json_dict.values()))))
AttributeError: 'str' object has no attribute 'values'
"
Traceback (most recent call last):
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 455, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 428, in process_template
    return tenv().get_template(template_name + '.md').render(**template_parameters)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zoni/.virtualenvs/err/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zoni/Workspace/Projects/err/errbot/core_plugins/templates/repos2.md", line 6, in top-level template code
    {% for repo in repos %}         | {{('**'+repo.entry_name+'**').ljust(22)}} | {{repo.documentation}}
  File "/home/zoni/Workspace/Projects/err/errbot/repo_manager.py", line 153, in search_repos
    if query_work_set.intersection(tokenizeJsonEntry(plugin)):
  File "/home/zoni/Workspace/Projects/err/errbot/repo_manager.py", line 66, in tokenizeJsonEntry
    return set(find_words.findall(' '.join((word.lower() for word in json_dict.values()))))
AttributeError: 'str' object has no attribute 'values'
```

**Comment by gbin** [comment]
It works for me...

Update from local source tools/repos.json  <- Can you try with the public entries ?

**Comment by zoni** [comment]
PEBKAC. I overlooked a BOT_PLUGIN_INDEXES setting that was pointing to a local repos.json still. Doh!
