### ISSUE TITLE
Some argparse issue, can't daemonize

### ISSUE THREAD

**Issue by nudzo** [errbotio/errbot#676]
Getting following exception when trying to run `errbot` as daemon:
```
10:05:21 INFO     errbot.err                Config check passed...
10:05:21 INFO     errbot.err                Selected backend 'Slack'.
10:05:21 INFO     errbot.err                Checking for '/home/errbot/data'...
Traceback (most recent call last):
  File "/home/errbot/.local/bin/errbot", line 9, in <module>
    load_entry_point('errbot==4.0.2', 'console_scripts', 'errbot')()
  File "/home/errbot/.local/lib/python3.5/site-packages/errbot/err.py", line 234, in main
    if args['text']:
KeyError: 'text'
```
Btw the same behaviour on FreeBSD and OSX... appeared since 4.0 version.

**Comment by zoni** [comment]
I'm sorry, this was my mistake. :disappointed: It should be fixed now though.
