### ISSUE TITLE
XMPP: !render test broken under py2.7 with xhtml-im

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#678]
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 0: invalid start byte
"
Traceback (most recent call last):
  File "/home/gbin/projects/errbot/errbot/errBot.py", line 456, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/home/gbin/projects/errbot/errbot/errBot.py", line 212, in send_simple_reply
    self.split_and_send_message(reply)
  File "/home/gbin/projects/errbot/errbot/errBot.py", line 186, in split_and_send_message
    self.send_message(partial_message)
  File "/home/gbin/projects/errbot/errbot/backends/xmpp.py", line 511, in send_message
    mhtml = xhtmlim.unescape(self.md_xhtml.convert(mess.body)) if self.xhtmlim else None
  File "/home/gbin/projects/errbot/errbot/rendering/xhtmlim.py", line 102, in unescape
    return _charref.sub(_replace_charref, s)
  File "/home/gbin/projects/errbot/errbot/rendering/xhtmlim.py", line 89, in _replace_charref
    return SAFE_ENTITIES[s[:x]] + s[x:]
  File "/home/gbin/.virtualenvs/err-py2/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 0: invalid start byte
```

**Comment by zoni** [comment]
We've dropped Python 2 support so this can be closed.
