### ISSUE TITLE
Unable to use self.send() with Slack backend - TypeError: unhashable type: 'SlackBackend'

### ISSUE THREAD

**Issue by keithsharp** [errbotio/errbot#679]
Using Slack backend and Python 3.4 on Fedora 23, I am unable to call the self.send() method in my bot.  Example method:

```
@botcmd
def hello(self, msg, args):
    self.send(self.build_identifier('@keith'), "Hello, world!")
    return None
```

When I send the bot the !hello message, either in a room or direct, I get the following log message and traceback:

```
15:36:50 INFO     errbot.plugins.ACLS       Check if hello is admin only command.
15:36:50 INFO     errbot.errBot             Processing command 'hello' with parameters '' from @keith
15:36:50 ERROR    errbot.errBot             An error happened while processing a message ("!hello"): Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/errbot/errBot.py", line 465, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/errbot/plugin/oneview.py", line 14, in hello
    self.send(self.build_identifier('@keith'), "Hello, world!")
  File "/usr/lib/python3.4/site-packages/errbot/botplugin.py", line 425, in build_identifier
    return self._bot.build_identifier(txtrep)
  File "/usr/lib/python3.4/site-packages/errbot/backends/slack.py", line 582, in build_identifier
    return SlackIdentifier(self.sc, userid, self.get_im_channel(userid))
  File "/usr/lib64/python3.4/functools.py", line 458, in wrapper
    key = make_key(args, kwds, typed)
  File "/usr/lib64/python3.4/functools.py", line 382, in _make_key
    return _HashedSeq(key)
  File "/usr/lib64/python3.4/functools.py", line 351, in __init__
    self.hashvalue = hash(tup)
TypeError: unhashable type: 'SlackBackend'
"
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/errbot/errBot.py", line 465, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/errbot/plugin/oneview.py", line 14, in hello
    self.send(self.build_identifier('@keith'), "Hello, world!")
  File "/usr/lib/python3.4/site-packages/errbot/botplugin.py", line 425, in build_identifier
    return self._bot.build_identifier(txtrep)
  File "/usr/lib/python3.4/site-packages/errbot/backends/slack.py", line 582, in build_identifier
    return SlackIdentifier(self.sc, userid, self.get_im_channel(userid))
  File "/usr/lib64/python3.4/functools.py", line 458, in wrapper
    key = make_key(args, kwds, typed)
  File "/usr/lib64/python3.4/functools.py", line 382, in _make_key
    return _HashedSeq(key)
  File "/usr/lib64/python3.4/functools.py", line 351, in __init__
    self.hashvalue = hash(tup)
TypeError: unhashable type: 'SlackBackend'
```

**Comment by gbin** [comment]
This is strange, that's for this error that we added this `__hash__` method here https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L473

Which version of errbot do you use ?

**Comment by keithsharp** [comment]
Doh, I was using the latest from GitHub, but when I checked my container was using a cached build from a a couple of weeks back!  Updating to head solves the problem.

Thanks for the quick response.
