### ISSUE TITLE
Slack channel message failing

### ISSUE THREAD

**Issue by ethan-eb** [errbotio/errbot#713]
I am using the Redis storage backend, and trying to send a message to a slack channel. I have a "channel subscriber" list which contains:

    127.0.0.1:6379[2]> get errbot:EBEvents:ff-channel-subscribers-qa
    "[\"C0NH8QPV5\"]"

To update channel subscribers I'm doing this:

        channels_list = self._storage_list(channels_key)
        for c in channels_list:
            if self._bot.mode == 'slack':
                c = '<#%s>' % c
            self.send(self.build_identifier(c), msg)

However I seem to be falling into a DIVERT_TO_PRIVATE issue? (My DIVERT_TO_PRIVATE == ()) related to #437 maybe ...
  
    Traceback (most recent call last):
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 459, in send_message
        to_channel_id = self.get_im_channel(self.username_to_userid(mess.to.username))
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 394, in username_to_userid
        raise UserDoesNotExistError(u"Cannot find user %s" % name)
    UserDoesNotExistError: Cannot find user <None>

Not clear to me why `startswith('C')` would result in a `username_to_userid` call (in slack.py)?

                if to_channel_id.startswith('C'):
                    log.debug("This is a divert to private message, sending it directly to the user.")
                    to_channel_id = self.get_im_channel(self.username_to_userid(mess.to.username))

**Comment by zoni** [comment]
I can't directly tell why this would failing the way you describe. A little DEBUG-level log output leading up the the Traceback you receive might be helpful here.

That said though, is there a specific reason why you want/need to store the Slack channel ID itself? If not, I think it might be better to store the string representation of the `Identifier` object you received instead (you can build an Identifier from that the same way, using `self.build_identifier()`).

**Comment by ethan-eb** [comment]
Debug didn't give me much more ... very similar code to update a User says:

    2016-04-12 12:47:10,442 DEBUG    errbot.backends.slack     building an identifier from <@U027ENK8E>
    2016-04-12 12:47:10,511 DEBUG    errbot.backends.slack     Sending direct message to ethan (D0K68UZUM)

Whereas for a channel

    2016-04-12 12:47:10,520 DEBUG    errbot.backends.slack     building an identifier from <#C0NH8QPV5>
    2016-04-12 12:47:10,522 ERROR    errbot.backends.slack     Cannot find user with ID None
    2016-04-12 12:47:10,522 DEBUG    errbot.backends.slack     This is a divert to private message, sending it directly to the user.
    2016-04-12 12:47:10,524 ERROR    errbot.backends.slack     Cannot find user with ID None
    2016-04-12 12:47:10,524 ERROR    errbot.backends.slack     An exception occurred while trying to send the following message to <None>: QA: *log_user_permission_activity* set to `disabled for everyone` on 2016-04-12 12:45
    Traceback (most recent call last):
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 459, in send_message
        to_channel_id = self.get_im_channel(self.username_to_userid(mess.to.username))
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 394, in username_to_userid
        raise UserDoesNotExistError(u"Cannot find user %s" % name)
    UserDoesNotExistError: Cannot find user <None>

I am willing to follow your suggestion, but not sure how. Started a G+ thread: https://plus.google.com/114875040601110763500/posts/JXuVFoRQBEP

**Comment by ethan-eb** [comment]
Well, I have switched to the string representation of the channel, verified in redis

    127.0.0.1:6379[2]> get errbot:EBEvents:ff-channel-subscribers-qa
    "[\"#qa-feature-flags\"]"

I have also stopped the `<#%s> % c` business, so it is just calling:

        for c in channels_list:
            self.send(self.build_identifier(c), msg)

And I still have the same error 😢 `UserDoesNotExistError: Cannot find user <None>` on the same lines in slack.py

**Comment by ethan-eb** [comment]
Once more with debug...

    2016-04-13 12:07:00,365 DEBUG    errbot.plugins.ebevents   Trying to send to #qa-feature-flags
    2016-04-13 12:07:00,366 DEBUG    errbot.backends.slack     building an identifier from #qa-feature-flags
    2016-04-13 12:07:00,367 ERROR    errbot.backends.slack     Cannot find user with ID None
    2016-04-13 12:07:00,367 DEBUG    errbot.backends.slack     This is a divert to private message, sending it directly to the user.
    2016-04-13 12:07:00,368 ERROR    errbot.backends.slack     Cannot find user with ID None
    2016-04-13 12:07:00,369 ERROR    errbot.backends.slack     An exception occurred while trying to send the following message to <None>: QA: *log_user_permission_activity* set to `active for User Events@fsb.org.uk` on 2016-04-13 12:06
    Traceback (most recent call last):
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 459, in send_message
        to_channel_id = self.get_im_channel(self.username_to_userid(mess.to.username))
      File "/usr/local/www/evbot/releases/current/venv/lib/python2.7/site-packages/errbot/backends/slack.py", line 394, in username_to_userid
        raise UserDoesNotExistError(u"Cannot find user %s" % name)
    UserDoesNotExistError: Cannot find user <None>

It must be, first of all, a failure in `is_group` https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L450-L462 ... it seems like I should be falling into the first `if` there, but I'm not because I'm arriving at `startswith('C')` bit ...

**Comment by zoni** [comment]
Yeah, I can confirm the issue, this is definitely a bug. I'm putting this at the top of my list, but doubt I'll get a chance to really dig into this until some time during the weekend.

**Comment by gbin** [comment]
I am trying to reproduce, simply DIVERT_TO_PRIVATE is broken on Slack as far as I see. I am trying to figure our what is going on.

**Comment by gbin** [comment]
Please reopen if my fix did not fix your specific problem.

**Comment by yolkov** [comment]
I want to send message to group
        self.send(
            self.build_identifier("<@C12J64LRX>"),
            "Boo! Bet you weren't expecting me, were you?",
        )
where <@C12J64LRX> - slack channel

2016-05-10 10:45:23,965 DEBUG    errbot.backends.slack     building an identifier from <@C12J64LRX>
2016-05-10 10:45:23,966 ERROR    errbot.backends.slack     Cannot find user with ID None
2016-05-10 10:45:23,966 ERROR    errbot.backends.slack     An exception occurred while trying to send the following message to <None>: Boo! Bet you weren't expecting me, were you?
Traceback (most recent call last):
  File "/home/deployer/bot/lib/python3.4/site-packages/errbot/backends/slack.py", line 459, in send_message
    to_channel_id = mess.to.channel
AttributeError: 'SlackPerson' object has no attribute 'channel'

**Comment by didiersmith** [comment]
With the latest fix, I still ran into this issue when using the self.build_identifier("#channel") format. The issue is fixed, however, when using the self.build_identifier(u"<#channel_id>") format.

I believe that this is because if a channel name is given, a SlackRoomOccupant is returned: https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L662

But if a channel ID is given, a SlackPerson is returned (a few lines above). 

The fix in 6e68583 checks to see if the recipient is a RoomOccupant, so that check triggers if a channel name is given but not a channel id. So I think to fix this completely, L662 needs to return a SlackPerson instead.

**Comment by ethan-eb** [comment]
I am also still stuck on this

    Traceback (most recent call last):
      File "/usr/local/www/evbot/releases/current/venv/lib/python3.5/site-packages/errbot/backends/slack.py", line 487, in send_message
        to_channel_id = self.get_im_channel(self.username_to_userid(mess.to.username))
      File "/usr/local/www/evbot/releases/current/venv/lib/python3.5/site-packages/errbot/backends/slack.py", line 406, in username_to_userid
        raise UserDoesNotExistError("Cannot find user %s" % name)
    errbot.backends.base.UserDoesNotExistError: Cannot find user <None>

**Comment by ethan-eb** [comment]
I don't believe I can re-open the ticket

**Comment by gbin** [comment]
@ethan-eb please reopen another one with a your reproduction case
