### ISSUE TITLE
No error message on plugin configuration exception

### ISSUE THREAD

**Issue by cweiske** [errbotio/errbot#736]
When plugin configuration fails (`check_configuration` raises a `errbot.utils.ValidationException`), I still get the message "Plugin configuration done.".

There should be an error message to the user instead.

Example:
```
 >>> !plugin config exec {'command': 'failure'}
20:42:25 INFO     errbot.plugins.ACLS       Matching ACL {} against username gbin@localhost for command Plugins:plugin_config
20:42:25 INFO     errbot.plugins.ACLS       Check if plugin_config is admin only command.
20:42:25 INFO     errbot.errBot             Processing command 'plugin_config' with parameters 'exec {'command': 'failure'}' from gbin@localhost
20:42:26 INFO     errbot.plugin_manager     Activating exec with min_err_version = 4.0.0 and max_version = 4.0.99
20:42:26 ERROR    errbot.plugin_manager     Something is wrong with the configuration of the plugin exec
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/plugin_manager.py", line 277, in activate_plugin_with_version_check
    obj.check_configuration(config)
  File "/home/cweiske/Dev/tools/xmppexecbot/exec.py", line 44, in check_configuration
    self.executable_exists(configuration['command'])
  File "/home/cweiske/Dev/tools/xmppexecbot/exec.py", line 31, in executable_exists
    raise ValidationException('Command not in PATH')
ValidationException: Command not in PATH
20:42:26 ERROR    errbot.plugin_manager     Error loading exec
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/plugin_manager.py", line 452, in activate_plugin
    self.activate_plugin_with_version_check(name, self.get_plugin_configuration(name))
  File "/usr/local/lib/python2.7/dist-packages/errbot/plugin_manager.py", line 283, in activate_plugin_with_version_check
    raise PluginConfigurationException(unicode(ex))
PluginConfigurationException: Command not in PATH
 
╌╌[MD  ]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
Plugin configuration done.
```

**Comment by gbin** [comment]
Yep confirmed, I am trying to fix this ...

**Comment by gbin** [comment]
fixed + added non regression test. Thanks for the precise report !
