### ISSUE TITLE
build_identifier('#room') on Slack doesn't produce a Room

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#778]
This is part of the new contract, I have added it to the backend tester.

It even crashes on Slack because the comparison between identifiers is sloppy:
```
Traceback (most recent call last):
  File "/Users/gbin/projects/errbot/errbot/core.py", line 452, in _execute_and_send
    for reply in replies:
  File "/Users/gbin/projects/errbot-plugins/err-backend-tester/betester.py", line 48, in public
    if mess.to != self.build_identifier(str(mess.to)):
  File "/Users/gbin/projects/errbot/errbot/backends/slack.py", line 912, in __eq__
    return self.id == other.id
AttributeError: 'SlackPerson' object has no attribute 'id'
```

**Comment by gbin** [comment]
Fixed by 0e7652da523e6abdede9657e0883da476d8ead03
