### ISSUE TITLE
pytest should be either a hard dependency of errbot or not load

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#841]
For example here, trying to load the Text backend:

14:36:48 ERROR    yapsy                     Unable to import plugin: /home/epolger/Projects/NotOwn/errbot/lib/python3.4/site-packages/errbot/backends/text
Traceback (most recent call last):
  File "/home/epolger/Projects/NotOwn/errbot/lib/python3.4/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/epolger/Projects/NotOwn/errbot/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/epolger/Projects/NotOwn/errbot/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/epolger/Projects/NotOwn/errbot/lib/python3.4/site-packages/errbot/backends/text.py", line 16, in <module>
    from errbot.backends.test import TestPerson
  File "/home/epolger/Projects/NotOwn/errbot/lib/python3.4/site-packages/errbot/backends/test.py", line 10, in <module>
    import pytest
ImportError: No module named 'pytest'

**Comment by zoni** [comment]
This regression seems to be causing people real trouble because it breaks `errbot --text` on new installs. Since pytest is used for testing only, the text backend (or any other, for that matter) really shouldn't try to import it.

Adding pytest as a regular dependency is a workaround for this, but I don't like forcing development dependencies onto users.

**Comment by mrshu** [comment]
@zoni @gbin could the [pytest fixture](https://github.com/errbotio/errbot/blob/master/errbot/backends/test.py#L500) be moved somewhere else? It seems that that would be easier than requiring `pytest` to be installed.

**Comment by zoni** [comment]
> @zoni @gbin could the pytest fixture be moved somewhere else? It seems that that would be easier than requiring pytest to be installed.

That would be less than ideal because it would be breaking the API (people may be importing the fixture from that module for their tests).

I think the core issue here is that the text backend shouldn't try to just import stuff from the test backend and have tried to address this with #844. Long term we should probably provide a better "local" backend infrastructure which can be shared by both the text as well as the test backend which would provide a good emulation of a real chat network (right now it's kind of hacked together without a really good thought out design because it's grown organically over time).
