### ISSUE TITLE
can not invoke `api_call` method

### ISSUE THREAD

**Issue by zhangsm** [errbotio/errbot#883]
```python
@botcmd
def hi(self, msg, args):
    sb = slack.SlackBackend(self)
    response = sb.api_call('chat.postMessage', data={
        'channel': "#caerus-alert",
        'text': "My message text here",
        'unfurl_media': 'true',
        'as_user': 'true',
    })
    log.info(response)
    return 'hi, It *works* ! haha ~'
```

can not working, like this

```bash
 >>> !hi
Computer says nooo. See logs for details:
 'Hello' object has no attribute 'BOT_PREFIX'
```

daemon log
```
2016-10-25 17:11:35,833 ERROR    errbot.core               An error happened while processing a message ("!hi"): Traceback (most recent call last):
  File "/Users/mike/.virtualenv3/lib/python3.5/site-packages/errbot/core.py", line 455, in _execute_and_send
    reply = method(mess, match) if match else method(mess, args)
  File "/Users/mike/workspaces/zhangsm/hatter/plugins/hello/hello.py", line 25, in hi
    sb = slack.SlackBackend(config)
  File "/Users/mike/.virtualenv3/lib/python3.5/site-packages/errbot/backends/slack.py", line 236, in __init__
    super().__init__(config)
  File "/Users/mike/.virtualenv3/lib/python3.5/site-packages/errbot/core.py", line 50, in __init__
    self.prefix = bot_config.BOT_PREFIX
AttributeError: 'NoneType' object has no attribute 'BOT_PREFIX'
```

**Comment by zoni** [comment]
Don't try to initialize your own instance of `SlackBackend`, it's not designed for that. :smile: 

Errbot already provides access to the underlying slackclient instance you need, as documented in the guide on [getting to the bot object](http://errbot.io/en/latest/user_guide/plugin_development/backend_specifics.html#getting-to-the-bot-object).

Basically you should do:

```python
@botcmd
def hi(self, msg, args):
    response = self._bot.sc.api_call('chat.postMessage', data={
        'channel': "#caerus-alert",
        'text': "My message text here",
        'unfurl_media': 'true',
        'as_user': 'true',
    })
    log.info(response)
    return 'hi, It *works* ! haha ~'
```

Obligatory disclaimer: While unlikely to change, this interface comes with no guarantees about API stability.
