### ISSUE TITLE
error when execute a long time fab command

### ISSUE THREAD

**Issue by hanks** [errbotio/errbot#905]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.4
* OS version: ubuntu 14.04
* Python version: 3.4
* Using a virtual environment: yes

### Issue description

I want to use errbot as a deploy chatbot in hipchat, and I use fab to execute the deploy in the plugin implementation. But when I execute the plugin, it can execute some short fab command, but when to a long-item fab command, it does not work. 

### Additional info

error message is like below:

```
2016-11-21 12:34:34,714 WARNING  sleekxmpp.xmlstream.handler.waiter Timed out waiting for IqWait_15d8ae9e-68d2-46ce-a294-89ec92624f6f-21
2016-11-21 12:34:34,714 ERROR    sleekxmpp.xmlstream.xmlstream Error processing event handler: <bound method HipchatClient.session_start of <y
apsy_loaded_plugin_Hipchat_0.HipchatClient object at 0x7f5b0abacb38>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/xmpp.py", line 333, in session_start
    self.client.get_roster()
  File "/usr/local/lib/python3.4/dist-packages/sleekxmpp/clientxmpp.py", line 258, in get_roster
    response = iq.send(block, timeout, callback)
  File "/usr/local/lib/python3.4/dist-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq id="15d8ae9e-68d2-46ce-a294-89ec92624f6f-21" type="get"><query xmlns="jabber:iq:roster" /></iq>
2016-11-21 12:34:34,715 ERROR    sleekxmpp.basexmpp        Request timed out: <iq id="15d8ae9e-68d2-46ce-a294-89ec92624f6f-21" type="get"><que
ry xmlns="jabber:iq:roster" /></iq>
2016-11-21 12:34:34,715 WARNING  sleekxmpp.basexmpp        You should catch IqTimeout exceptions
```

```
2016-11-21 12:37:22,098 ERROR    sleekxmpp.xmlstream.xmlstream Socket Error #104: Connection reset by peer
2016-11-21 12:37:22,099 WARNING  sleekxmpp.xmlstream.xmlstream Failed to send b'</stream:stream>'
2016-11-21 12:37:22,100 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2016-11-21 12:37:22,105 INFO     sleekxmpp.xmlstream.xmlstream Waiting for </stream:stream> from server
2016-11-21 12:37:22,106 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
```

**Comment by zoni** [comment]
What's the value of `BOT_ASYNC` in your `config.py`? And do you have a minimal plugin example you could show us that has this problem? (Do you run into the same problem with a long `time.sleep` call as opposed to a long-running fabric call?)

**Comment by hanks** [comment]
@zoni Thank you for your reply,  I use `BOT_ASYNC = True`, and plugin code is like below, I put all the related codes into a class:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import subprocess

from errbot import botcmd, BotPlugin

class Deploy(BotPlugin):
    """
    """
    @botcmd
    def fab(self, message, args):
        """fab command for deploy plugin

        Args:
            message: Message object
            args: str, like `fab --list`, args will be `--list` with leading space

        Returns:
            str, command execution result
        """
        yield 'hello'

        result = self._fab(args.strip())

        yield result

    @staticmethod
    def _fab(fab_option):
        """Fab command helper

        Args:
            fab_option: str, like `--list`

        Returns:
            str, command result
        """
        cmd = '{} {}'.format('fab', fab_option)
        output = self.execute_command(cmd)

        return output
 
    @staticmethod
    def execute_command(cmd):
        """Execute command with path specified or not

        Args:
            cmd: str, command string, like `which python`

        Returns:
            str, command execution result
        """
        try:
            output = subprocess.check_output(cmd, shell=True)
        except Exception as e:
            output = 'command {} error! {}'.format(cmd, str(e))

        if isinstance(output, bytes):
            output = output.decode()

        return output
```

I did not test `time.sleep`, and will test it later.

**Comment by zoni** [comment]
Not seeing anything unusual in your plugin, that should just work. I look forward to hearing whether you have the same issues with a simple `time.sleep` or not.

**Comment by hanks** [comment]
@zoni I tried `time.sleep`, and it works.

```python
    @botcmd
    def fab(self, message, args):
        """fab command for deploy plugin

        Args:
            message: Message object
            args: str, like `fab --list`, args will be `--list` with leading space

        Returns:
            str, command execution result
        """
        yield 'foo'

        time.sleep(80)

        yield 'bar'
```

**Comment by zoni** [comment]
That's interesting. So it doesn't appear to have anything to do with how long the execution takes.

Maybe something about the output makes HipChat unhappy? What happens when, instead of returning the output from `fab` as one big text, you yield it line-by-line?

**Comment by sheluchin** [comment]
I wrote a Fabric plugin recently as well. You might want to take a look and see if you find it helpful: https://github.com/netquity/err-fabric Do note that it was written with Slack in mind, but might work with HipChat with few modifications or none at all.

**Comment by hanks** [comment]
@zoni  @sheluchin Thank you for your reply,  and finally I found the reason of the error, because I use `fabric.colors`  to make output message colorful, and as zoni said,  it makes HipChat or sleekxmpp lib unhappy.
