### ISSUE TITLE
4.2.2 does not install on OS X <= 10.11 Python 2.7

### ISSUE THREAD

**Issue by vitorio** [errbotio/errbot#922]
### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: 4.1.3
* OS version: OS X El Capitan 10.11.6
* Python version: 2.7.10
* Using a virtual environment: no

### Issue description

OS X El Capitan 10.11 and earlier ship Python 2.7 and setuptools 1.1.6.  This causes problems for packages which expect features present in newer versions of setuptools, such as entrypoints or, in the case of errbot, `include`.  Attempting to install errbot 4.2.2, what should be the last version of errbot to support OS X 10.11, fails:

```console
$ ~/Library/Python/2.7/bin/pip install --user --upgrade errbot==4.2.2
Collecting errbot==4.2.2
  Downloading errbot-4.2.2.tar.gz (193kB)
    100% |████████████████████████████████| 194kB 2.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g7/8jvvxkfs1bq0w_pj_cdxp65c0000gn/T/pip-build-MQf3Jt/errbot/setup.py", line 127, in <module>
        packages = find_packages(src_root, include=['errbot', 'errbot.*'])
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g7/8jvvxkfs1bq0w_pj_cdxp65c0000gn/T/pip-build-MQf3Jt/errbot/
```

errbot 4.1.3 is the last version that supports Python 2.7 which successfully installs on OS X.  The changes in this commit broke it:  https://github.com/errbotio/errbot/commit/4eb0e465873c15fb0cc5d90aed0711cbc5489b56#diff-2eeaed663bd0d25b7e608891384b7298

Reverting those changes should fix the problem in the 4.2 line.

Alternatively, `setup.py` could check for and use an updated version of setuptools in the userdir, using code like this:

```python
import io, sys, platform
import markdown, jinja2, pdfkit, frontmatter, pdfrw

## markdown's codehilite extension uses Pygments
## Pygments uses setuptools' "entrypoints" system for plugins
## OS X El Capitan ships an old setuptools without entrypoints
## OS X El Capitan doesn't let you upgrade setuptools because of SIP
## So, change Python's search path to find the userdir setuptools instead
## macOS Sierra ships a more recent setuptools, and everyone else is on their own
if platform.platform().startswith('Darwin'):
  osxver = [int(x) for x in platform.mac_ver()[0].split('.')]
  if osxver[0] <= 10 and osxver[1] <= 11:
    sys.path = [x for x in sys.path if x.startswith('/Users')] + [x for x in sys.path if not x.startswith('/Users')]
```

### Steps to reproduce

Attempt to install errbot 4.2/4.2.1/4.2.2 on OS X <= 10.11 (macOS Sierra 10.12 ships a newer version of setuptools).

### Additional info

Force-upgrading the system setuptools with sudo is not an option on OS X 10.11 because of the new System Integrity Protection feature.  Asking users to disable a critical part of OS X's security to install errbot is unreasonable.  https://support.apple.com/en-us/HT204899

**Comment by r3m0t** [comment]
Perhaps the docs should be updated stating a virtualenv may be required on platforms with outdated setuptools? Is there any disadvantage to using a virtualenv in your case?

**Comment by vitorio** [comment]
@r3m0t I don't know, I don't develop using virtualenv.

However, I ship my errbot bot to non-developer end-users on OS X, and anything more complicated than a few terminal commands, that puts their machine in an atypical state (such as when "activating" a virtualenv), is risky from my perspective.

I can try it out, see how it works, and report back, if that's the preferred solution.

**Comment by r3m0t** [comment]
Maybe a maintainer will help you out, but FYI, virtualenvs can be used without being "activated", like this:

```bash
virtualenv errbot_env  #creates env
errbot_env/bin/pip install -U setuptools
errbot_env/bin/pip install errbot[slack]
errbot_env/bin/errbot -c config.py
```

**Comment by vitorio** [comment]
On OS X 10.11.6, using virtualenv seems to work, and doesn't appear to be any more onerous than without virtualenv:

```console
$ easy_install --user pip
Searching for pip
Best match: pip 9.0.0
Adding pip 9.0.0 to easy-install.pth file
Installing pip script to /Users/username/Library/Python/2.7/bin
Installing pip3.5 script to /Users/username/Library/Python/2.7/bin
Installing pip3 script to /Users/username/Library/Python/2.7/bin

Using /Users/username/Library/Python/2.7/lib/python/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
$ ~/Library/Python/2.7/bin/pip install --user virtualenv
Collecting virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 331kB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
$ cd Documents/
$ mkdir errbot-dev2
$ cd errbot-dev2/
$ ~/Library/Python/2.7/bin/virtualenv env
New python executable in /Users/username/Documents/errbot-dev2/env/bin/python
Installing setuptools, pip, wheel...done.
$ ./env/bin/pip install errbot==4.2.2
Collecting errbot==4.2.2
Collecting docutils (from errbot==4.2.2)
Collecting pygments-markdown-lexer>=0.1.0.dev39 (from errbot==4.2.2)
Collecting config (from errbot==4.2.2)
Collecting yapsy>=1.11 (from errbot==4.2.2)
Collecting typing (from errbot==4.2.2)
Collecting backports.functools-lru-cache (from errbot==4.2.2)
  Using cached backports.functools_lru_cache-1.3-py2.py3-none-any.whl
Collecting ansi (from errbot==4.2.2)
Collecting daemonize (from errbot==4.2.2)
  Using cached daemonize-2.4.7-py2.py3-none-any.whl
Collecting configparser>=3.5.0b2 (from errbot==4.2.2)
Collecting colorlog (from errbot==4.2.2)
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting bottle (from errbot==4.2.2)
  Using cached bottle-0.12.10-py2-none-any.whl
Collecting rocket-errbot (from errbot==4.2.2)
Collecting pytest-xdist (from errbot==4.2.2)
Collecting pep8 (from errbot==4.2.2)
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting jinja2 (from errbot==4.2.2)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting webtest (from errbot==4.2.2)
  Using cached WebTest-2.0.23-py2.py3-none-any.whl
Collecting Pygments>=2.0.2 (from errbot==4.2.2)
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Collecting dnspython (from errbot==4.2.2)
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting markdown (from errbot==4.2.2)
Collecting threadpool (from errbot==4.2.2)
  Using cached threadpool-1.3.2-py2-none-any.whl
Collecting PyOpenSSL (from errbot==4.2.2)
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting pytest (from errbot==4.2.2)
  Using cached pytest-3.0.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./env/lib/python2.7/site-packages (from errbot==4.2.2)
Collecting mock (from errbot==4.2.2)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting requests (from errbot==4.2.2)
  Using cached requests-2.12.3-py2.py3-none-any.whl
Collecting execnet>=1.1 (from pytest-xdist->errbot==4.2.2)
  Using cached execnet-1.4.1-py2.py3-none-any.whl
Collecting py>=1.4.22 (from pytest-xdist->errbot==4.2.2)
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting MarkupSafe (from jinja2->errbot==4.2.2)
Collecting WebOb>=1.2 (from webtest->errbot==4.2.2)
  Using cached WebOb-1.6.3-py2.py3-none-any.whl
Collecting beautifulsoup4 (from webtest->errbot==4.2.2)
  Using cached beautifulsoup4-4.5.1-py2-none-any.whl
Collecting six (from webtest->errbot==4.2.2)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting waitress>=0.8.5 (from webtest->errbot==4.2.2)
  Using cached waitress-1.0.1-py2.py3-none-any.whl
Collecting cryptography>=1.3.4 (from PyOpenSSL->errbot==4.2.2)
  Using cached cryptography-1.6-cp27-cp27m-macosx_10_10_intel.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock->errbot==4.2.2)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->errbot==4.2.2)
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting apipkg>=1.4 (from execnet>=1.1->pytest-xdist->errbot==4.2.2)
  Using cached apipkg-1.4-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
  Using cached cffi-1.9.1-cp27-cp27m-macosx_10_10_intel.whl
Collecting pyasn1>=0.1.8 (from cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting enum34 (from cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4->PyOpenSSL->errbot==4.2.2)
Installing collected packages: docutils, Pygments, pygments-markdown-lexer, config, yapsy, typing, backports.functools-lru-cache, ansi, daemonize, configparser, colorlog, bottle, rocket-errbot, apipkg, execnet, py, pytest, pytest-xdist, pep8, MarkupSafe, jinja2, WebOb, beautifulsoup4, six, waitress, webtest, dnspython, markdown, threadpool, pycparser, cffi, pyasn1, idna, ipaddress, enum34, cryptography, PyOpenSSL, funcsigs, pbr, mock, requests, errbot
Successfully installed MarkupSafe-0.23 PyOpenSSL-16.2.0 Pygments-2.1.3 WebOb-1.6.3 ansi-0.1.3 apipkg-1.4 backports.functools-lru-cache-1.3 beautifulsoup4-4.5.1 bottle-0.12.10 cffi-1.9.1 colorlog-2.10.0 config-0.3.9 configparser-3.5.0 cryptography-1.6 daemonize-2.4.7 dnspython-1.15.0 docutils-0.12 enum34-1.1.6 errbot-4.2.2 execnet-1.4.1 funcsigs-1.0.2 idna-2.1 ipaddress-1.0.17 jinja2-2.8 markdown-2.6.7 mock-2.0.0 pbr-1.10.0 pep8-1.7.0 py-1.4.31 pyasn1-0.1.9 pycparser-2.17 pygments-markdown-lexer-0.1.0.dev39 pytest-3.0.5 pytest-xdist-1.15.0 requests-2.12.3 rocket-errbot-1.2.5 six-1.10.0 threadpool-1.3.2 typing-3.5.2.2 waitress-1.0.1 webtest-2.0.23 yapsy-1.11.223
$ ./env/bin/errbot 
03:38:31 ERROR    errbot.cli                I cannot find the config file /Users/username/Documents/errbot-dev2/config.py 
(You can change this path with the -c parameter see --help)
03:38:31 INFO     errbot.cli                You can use the template /Users/username/Documents/errbot-dev2/env/lib/python2.7/site-packages/errbot/cli.pyc/config-template.py as a base and copy it to /Users/username/Documents/errbot-dev2/config.py. 
You can then customize it.
```

**Comment by zoni** [comment]
OSX ships with notoriously old versions of Python (and by extension pip/setuptools/etc). I'm totally sympathetic to your cause of shipping to end-users but we [strongly recommend](http://errbot.io/en/latest/user_guide/setup.html#option-2-installing-errbot-in-a-virtualenv-preferred) using virtualenv when deploying errbot. In addition to facilitating installing up-to-date versions of pip/setuptools this also doubles as insulation from contaminating your OS vendor installed/supplied python packages with versions pulled directly from pip.

I'm not knowledgeable about the situation with OSX, but with, say, Debian, installing errbot globally would trample over the system python packages installed by apt, Debian's package manager. That's risky because (a) Debian uses various Python scripts internally, which may not work with (likely newer) versions installed from pip and (b) an update to the Debian package could cause apt to install a different version. Because of the way Debian (python) packages work, it will not do so using the typical `pip install foo` method and because of that it could result in a completely broken package due to leftover files from your manually installed/upgraded version.

The ideal situation in your case would probably be to ship OSX `.dmg` images so your end-users have a typical application they can install like any other. I did some research, but it doesn't look like that is easy to do, which is very unfortunate. :(

Since the use of a virtualenv resolves your issue I am going to choose to close this as that is our preferred way of installation, but if you have any more questions or concerns by all means let us know and we can discuss it further.
