### ISSUE TITLE
AttributeError: type object 'Markdown' has no attribute 'ESCAPED_CHARS'

### ISSUE THREAD

**Issue by flmmartins** [errbotio/errbot#953]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X ] Reporting a bug
* [ ] Suggesting a new feature
* [X ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.2.2
* OS version: https://hub.docker.com/_/python/
* Python version: 2.7
* Using a virtual environment: Container

### Issue description

Hi,

We are using this bot a while now but suddenly (aka since yesterday) when I start it there's an error:

17:44:22 ERROR    yapsy                     Unable to import plugin: /usr/local/lib/python2.7/site-packages/errbot/backends/text
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/local/lib/python2.7/site-packages/errbot/backends/text.py", line 14, in <module>
    from errbot.rendering import ansi, text, xhtml, imtext
  File "/usr/local/lib/python2.7/site-packages/errbot/rendering/__init__.py", line 10, in <module>
    MD_ESCAPE_RE = re.compile(u'|'.join(re.escape(c) for c in Markdown.ESCAPED_CHARS))
AttributeError: type object 'Markdown' has no attribute 'ESCAPED_CHARS'
17:44:22 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/errbot/bootstrap.py", line 126, in setup_bot
    bot = backendpm.get_plugin_by_name(backend_name)
  File "/usr/local/lib/python2.7/site-packages/errbot/specific_plugin_manager.py", line 87, in get_plugin_by_name
    raise Exception(u'Error loading plugin %s:\nError:\n%s\n' % (name, formatted_error))
Exception: Error loading plugin Text:
Error:
<type 'exceptions.AttributeError'>:
  File "/usr/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/local/lib/python2.7/site-packages/errbot/backends/text.py", line 14, in <module>
    from errbot.rendering import ansi, text, xhtml, imtext
  File "/usr/local/lib/python2.7/site-packages/errbot/rendering/__init__.py", line 10, in <module>
    MD_ESCAPE_RE = re.compile(u'|'.join(re.escape(c) for c in Markdown.ESCAPED_CHARS))

Can you provide me with some tips on what might be the problem?

### Steps to reproduce

Well since this is a private bot I cannot provide additional information. It happen's when we start errbot

### Other info

Here's our docker file:
FROM python:2.7

COPY requirements.txt /var/errbot/requirements.txt
RUN pip install -r /var/errbot/requirements.txt

COPY . /var/errbot
WORKDIR /var/errbot
ENTRYPOINT ["errbot"]

Here's our config.py

BACKEND = 'XMPP'

BOT_DATA_DIR = '/var/errbot/data'
BOT_EXTRA_PLUGIN_DIR = '/var/errbot/plugins'

BOT_LOG_FILE = '/var/errbot/errbot.log'
BOT_LOG_LEVEL = logging.DEBUG

BOT_IDENTITY = {
    'username':secret
    'password': secret
    'server': secret
}

XMPP_CA_CERT_FILE = None

CHAT_ROOMS = ['secretroom']

CHATROOM_PRESENCE = map(lambda room: '%s@conference.%s' %
                        (room, os.environ['XMPP_SERVER']),
                        CHAT_ROOMS)

CHATROOM_FN = 'secretbot'

BOT_ALT_PREFIXES = ('bot', '!',)
BOT_ALT_PREFIX_SEPARATORS = (':', ',', ';')

STORAGE = 'Memory'

DIVERT_TO_PRIVATE = ()

BOT_ADMINS = ('fmartins*', )

**Comment by zoni** [comment]
I believe this is caused by a new release of [Markdown](https://pypi.python.org/pypi/Markdown). If you (or anyone else hitting this bug with the time to dig into this) could confirm that downgrading to a previous release of Markdown fixes the issue, that would be great.

Obviously we need to fix it, but I haven't had the time to (1) confirm that the above is indeed the cause and (2) how things moved and what the new API would be.

**Comment by gbin** [comment]
Working on it ;)

**Comment by gbin** [comment]
Found the root cause : https://github.com/waylan/Python-Markdown/commit/c70b2c4154d9b6e46f282c1f212c52e9fbfa5a07

**Comment by unixeO** [comment]
Markdown 3 still have the bug, you need to downgrade.
Example:
"module 'markdown' has no attribute 'version'"

**Comment by qwergram** [comment]
Same issue as well. Markdown v. 2.6.11 works fine.

**Comment by camposer** [comment]
Besides downgrading markdown, I had to modify this file:
vi venv/lib/python3.9/site-packages/errbot/rendering/__init__.py

Line 10: MD_ESCAPE_RE = re.compile('|'.join(re.escape(c) for c in Markdown().ESCAPED_CHARS))

The ESCAPED_CHARS variable is not a constant anymore, it's a class member. I saw many places in the code using markdown objects, so I guess there's a better fix for this.
