### ISSUE TITLE
Errbot crashes with valid Slack configuration on Mac

### ISSUE THREAD

**Issue by larsrehe** [errbotio/errbot#957]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.6
* OS version: Mac OS X 10.11.6
* Python version: 3.5.2
* Using a virtual environment: yes

### Issue description

Errbot configured for Slack crashes with the following exception:

11:41:36 ERROR    yapsy                     Unable to create plugin object: /Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/backends/slack
Traceback (most recent call last):
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/specific_plugin_manager.py", line 59, in instanciateElement
    return element(self._config)
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/backends/slack.py", line 290, in __init__
    self.token = identity.get('token', None)
AttributeError: 'str' object has no attribute 'get'
11:41:36 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/bootstrap.py", line 126, in setup_bot
    bot = backendpm.get_plugin_by_name(backend_name)
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/specific_plugin_manager.py", line 86, in get_plugin_by_name
    raise Exception('Error loading plugin %s:\nError:\n%s\n' % (name, formatted_error))
Exception: Error loading plugin Slack:
Error:
<class 'AttributeError'>:
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/specific_plugin_manager.py", line 59, in instanciateElement
    return element(self._config)
  File "/Users/larsrehe/projects/errbot_docker/errbot-ve/lib/python3.5/site-packages/errbot/backends/slack.py", line 290, in __init__
    self.token = identity.get('token', None)

### Steps to reproduce

Set the following options in the default config.py:
BACKEND = 'Slack'
BOT_IDENTITY = '<SLACK TOKEN>'
BOT_ADMINS = ('<SLACK USER>', )

Then started errbot from the command line

### Additional info

Seems to me there is a bit of a type mismatch. This here works for me to fix the issue:

11:35 $ git diff errbot/backends/slack.py
diff --git a/errbot/backends/slack.py b/errbot/backends/slack.py
index 3917d8c..5057f9a 100644
--- a/errbot/backends/slack.py
+++ b/errbot/backends/slack.py
@@ -286,8 +286,7 @@ class SlackBackend(ErrBot):

     def __init__(self, config):
         super().__init__(config)
-        identity = config.BOT_IDENTITY
-        self.token = identity.get('token', None)
+        self.token = config.BOT_IDENTITY if hasattr(config, 'BOT_IDENTITY') else False
         if not self.token:
             log.fatal(
                 'You need to set your token (found under "Bot Integration" on Slack) in '

**Comment by zoni** [comment]
Your settings are misconfigured. `BOT_IDENTITY` should be a dictionary containing a key `token`, not the token as a string directly. See http://errbot.io/en/latest/user_guide/configuration/slack.html#account-setup.

(We *could* add a check which does better checking of the type set in the config, but then we should probably overhaul it for all settings - I don't think it warrants keeping this specific issue open)

**Comment by larsrehe** [comment]
Ah, makes sense! Thanks!
